//! # Tabler Icons for Rinch
//!
//! This crate provides 5000+ free SVG icons from [Tabler Icons](https://tabler.io/icons)
//! for use in Rinch applications.
//!
//! ## Features
//!
//! - **5000+ icons** in both Outline and Filled styles
//! - **Type-safe** - Use enum variants instead of strings
//! - **Tree-shaking friendly** - Only icons you use are included in the binary
//! - **Consistent styling** - All icons render at 24x24 with `currentColor`
//!
//! ## Usage
//!
//! ```rust,ignore
//! use rinch::prelude::*;
//! use rinch_tabler_icons::{TablerIcon, render_tabler_icon};
//!
//! #[component]
//! fn my_component() -> NodeHandle {
//!     rsx! {
//!         div {
//!             {render_tabler_icon(__scope, TablerIcon::AlertCircle, Default::default())}
//!             "Alert!"
//!         }
//!     }
//! }
//! ```
//!
//! ## Styles
//!
//! Icons come in two styles:
//! - **Outline** (default) - Stroke-based line icons
//! - **Filled** - Solid filled icons
//!
//! ```rust,ignore
//! use rinch_tabler_icons::{TablerIcon, TablerIconStyle, render_tabler_icon};
//!
//! // Outline style (default)
//! render_tabler_icon(__scope, TablerIcon::Heart, Default::default());
//!
//! // Filled style
//! render_tabler_icon(__scope, TablerIcon::Heart, TablerIconStyle::Filled);
//! ```
//!
//! ## Credits
//!
//! Icons are from [Tabler Icons](https://tabler.io/icons) by Paweł Kuna,
//! licensed under the MIT License.

// Allow `rinch::core::X` paths generated by the rsx! macro to resolve inside this crate.
extern crate self as rinch;
#[doc(hidden)]
pub mod core {
    pub use rinch_core::*;
}

use rinch_core::dom::{NodeHandle, RenderScope};

// Include the generated code from build.rs
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

/// Options for rendering a Tabler icon.
#[derive(Debug, Clone, Default)]
pub struct TablerIconOptions {
    /// The style variant (Outline or Filled).
    pub style: TablerIconStyle,
    /// Optional CSS class to add to the SVG element.
    pub class: Option<String>,
    /// Size in pixels (default: 24).
    pub size: Option<u32>,
    /// Stroke width for outline icons (default: 2).
    pub stroke_width: Option<f32>,
}

/// Renders a Tabler icon to a NodeHandle.
///
/// # Arguments
///
/// * `scope` - The render scope for creating DOM nodes
/// * `icon` - The icon to render
/// * `style` - The style variant (Outline or Filled)
///
/// # Returns
///
/// A NodeHandle containing the SVG element.
///
/// # Example
///
/// ```rust,ignore
/// let icon = render_tabler_icon(__scope, TablerIcon::Home, TablerIconStyle::Outline);
/// container.append_child(&icon);
/// ```
pub fn render_tabler_icon(
    scope: &mut RenderScope,
    icon: TablerIcon,
    style: TablerIconStyle,
) -> NodeHandle {
    render_tabler_icon_with_options(
        scope,
        icon,
        TablerIconOptions {
            style,
            ..Default::default()
        },
    )
}

/// Renders a Tabler icon with custom options.
///
/// # Arguments
///
/// * `scope` - The render scope for creating DOM nodes
/// * `icon` - The icon to render
/// * `options` - Rendering options (style, class, size, stroke width)
///
/// # Returns
///
/// A NodeHandle containing the SVG element.
pub fn render_tabler_icon_with_options(
    scope: &mut RenderScope,
    icon: TablerIcon,
    options: TablerIconOptions,
) -> NodeHandle {
    let __scope = scope;
    let stroke_width = options.stroke_width.unwrap_or(2.0);

    // Use 1em when no explicit size — icons inherit from parent font-size.
    // Use pixel values when an explicit size is given.
    let size_css = match options.size {
        Some(px) => format!("{}px", px),
        None => "1em".to_string(),
    };
    let size_attr = match options.size {
        Some(px) => px.to_string(),
        None => "24".to_string(),
    };

    let inline_style = format!("width: {0}; height: {0}; flex-shrink: 0;", size_css);

    // Helper to build an empty SVG fallback
    fn empty_svg(scope: &mut RenderScope, size_attr: &str, inline_style: &str) -> NodeHandle {
        let __scope = scope;
        let svg = rinch_macros::rsx! {
            svg { viewBox: "0 0 24 24" }
        };
        svg.set_attribute("width", size_attr);
        svg.set_attribute("height", size_attr);
        svg.set_attribute("style", inline_style);
        svg
    }

    // Get the paths for the requested style, falling back to the other style
    let (paths, is_filled) = match options.style {
        TablerIconStyle::Outline => {
            if let Some(p) = icon.outline_paths() {
                (p, false)
            } else if let Some(p) = icon.filled_paths() {
                (p, true)
            } else {
                return empty_svg(__scope, &size_attr, &inline_style);
            }
        }
        TablerIconStyle::Filled => {
            if let Some(p) = icon.filled_paths() {
                (p, true)
            } else if let Some(p) = icon.outline_paths() {
                (p, false)
            } else {
                return empty_svg(__scope, &size_attr, &inline_style);
            }
        }
    };

    // Create SVG element with rsx for structure, then set dynamic attributes
    let svg = if is_filled {
        rinch_macros::rsx! {
            svg {
                xmlns: "http://www.w3.org/2000/svg",
                viewBox: "0 0 24 24",
                fill: "currentColor",
                stroke: "none",
            }
        }
    } else {
        rinch_macros::rsx! {
            svg {
                xmlns: "http://www.w3.org/2000/svg",
                viewBox: "0 0 24 24",
                fill: "none",
                stroke: "currentColor",
                stroke-linecap: "round",
                stroke-linejoin: "round",
            }
        }
    };
    // Set dynamic string attributes (rsx {expr} wraps non-literals in FnMut Effects
    // which can't own Strings — use set_attribute for computed values)
    svg.set_attribute("width", &size_attr);
    svg.set_attribute("height", &size_attr);
    svg.set_attribute("style", &inline_style);
    if !is_filled {
        svg.set_attribute("stroke-width", &stroke_width.to_string());
    }

    // Add path children
    for path_data in paths {
        let path_node = rinch_macros::rsx! { path {} };
        path_node.set_attribute("d", path_data);
        svg.append_child(&path_node);
    }

    // Add optional class
    if let Some(class) = &options.class {
        svg.set_attribute("class", class);
    }

    svg
}

/// Macro to create an icon with inline rendering.
///
/// This macro is a convenience wrapper around `render_tabler_icon`.
///
/// # Example
///
/// ```rust,ignore
/// // Basic usage
/// tabler_icon!(__scope, Home)
///
/// // With style
/// tabler_icon!(__scope, Home, Filled)
/// ```
#[macro_export]
macro_rules! tabler_icon {
    ($scope:expr, $icon:ident) => {
        $crate::render_tabler_icon(
            $scope,
            $crate::TablerIcon::$icon,
            $crate::TablerIconStyle::default(),
        )
    };
    ($scope:expr, $icon:ident, $style:ident) => {
        $crate::render_tabler_icon(
            $scope,
            $crate::TablerIcon::$icon,
            $crate::TablerIconStyle::$style,
        )
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_icon_count() {
        const { assert!(ICON_COUNT > 4000) };
    }

    #[test]
    fn test_icon_name() {
        assert_eq!(TablerIcon::AlertCircle.name(), "alert-circle");
        assert_eq!(TablerIcon::Home.name(), "home");
    }

    #[test]
    fn test_icon_has_styles() {
        // Most icons have outline
        assert!(TablerIcon::AlertCircle.has_outline());
        assert!(TablerIcon::Home.has_outline());

        // Some icons have filled variants
        assert!(TablerIcon::Heart.has_filled());
    }

    #[test]
    fn test_icon_paths() {
        let paths = TablerIcon::AlertCircle.outline_paths();
        assert!(paths.is_some());
        assert!(!paths.unwrap().is_empty());
    }

    #[test]
    fn test_all_icons_iteration() {
        assert_eq!(ALL_ICONS.len(), ICON_COUNT);
    }
}
