#!/usr/bin/env python3
"""Generate src/serialize/html_entities_table.rs from the HTML standard's
named character references.

    curl -o entities.json https://html.spec.whatwg.org/entities.json
    python3 tools/gen_html_entities.py entities.json > src/serialize/html_entities_table.rs

The table is not typed by hand and not edited: run this again when the
standard adds a name (it has not since 2014).
"""
import hashlib
import json
import sys

path = sys.argv[1]
raw = open(path, "rb").read()
entities = json.loads(raw)

# name (no "&", no ";") -> (characters, decodes with no ";")
names = {}
for key, value in entities.items():
    assert key.startswith("&")
    name = key[1:].rstrip(";")
    assert name.isascii() and name.isalnum(), key
    chars, legacy = names.get(name, (value["characters"], False))
    assert chars == value["characters"], key
    names[name] = (chars, legacy or not key.endswith(";"))
# Every name is listed with its ";"; some also without.
assert all(f"&{n};" in entities for n in names)

# Byte order, which is what `str::cmp` compares.
order = sorted(names, key=lambda n: n.encode())
legacy = [n for n in order if names[n][1]]


def literal(text, escape):
    """A Rust string literal over several lines."""
    out, line = [], ""
    for ch in text:
        piece = escape(ch)
        if len(line) + len(piece) > 88:
            out.append(line)
            line = ""
        line += piece
    out.append(line)
    return '"\\\n     ' + "\\\n     ".join(out) + '"'


def ends(lengths, flags=None):
    out, at, line = [], 0, "   "
    for i, n in enumerate(lengths):
        at += n
        assert at < 0x8000
        cell = f" {at | (0x8000 if flags and flags[i] else 0)},"
        if len(line) + len(cell) > 96:
            out.append(line)
            line = "   "
        line += cell
    out.append(line)
    return "\n".join(out)


values = [names[n][0] for n in order]
print(f"""// @generated by tools/gen_html_entities.py — do not edit.
//
// Source: https://html.spec.whatwg.org/entities.json
// sha256: {hashlib.sha256(raw).hexdigest()}
// {len(entities)} references: {len(order)} names, {len(legacy)} of which also decode with no `;`.

/// How many names there are.
pub(super) const COUNT: usize = {len(order)};

/// The longest name, in bytes.
pub(super) const MAX_NAME: usize = {max(map(len, order))};

/// The longest name that decodes with no `;`.
pub(super) const MAX_LEGACY: usize = {max(map(len, legacy))};

/// Bit of a [`NAME_ENDS`] entry: the name decodes with no `;`.
pub(super) const LEGACY: u16 = 0x8000;

/// Every name, in byte order, end to end.
pub(super) static NAMES: &str = {literal("".join(order), lambda c: c)};

/// Where each name ends in [`NAMES`], with [`LEGACY`].
#[rustfmt::skip]
pub(super) static NAME_ENDS: [u16; COUNT] = [
{ends([len(n) for n in order], [names[n][1] for n in order])}
];

/// What each name stands for (one or two characters), end to end.
pub(super) static VALUES: &str = {literal("".join(values), lambda c: f"\\u{{{ord(c):x}}}")};

/// Where each name's characters end in [`VALUES`], in bytes.
#[rustfmt::skip]
pub(super) static VALUE_ENDS: [u16; COUNT] = [
{ends([len(v.encode()) for v in values])}
];""")
