//! Build script that downloads Tabler Icons SVG data and generates Rust code.
//!
//! Downloads from: https://unpkg.com/@tabler/icons@latest/
//! - tabler-nodes-outline.json (outline style icons)
//! - tabler-nodes-filled.json (filled style icons)

use heck::ToUpperCamelCase;
use serde_json::Value;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

const OUTLINE_URL: &str = "https://unpkg.com/@tabler/icons@3.36.1/tabler-nodes-outline.json";
const FILLED_URL: &str = "https://unpkg.com/@tabler/icons@3.36.1/tabler-nodes-filled.json";
const ICONS_JSON_URL: &str = "https://unpkg.com/@tabler/icons@3.36.1/icons.json";

/// Type alias for icon path data: (outline_paths, filled_paths)
type IconPaths = (Option<Vec<String>>, Option<Vec<String>>);

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated.rs");

    // Download icon data
    eprintln!("Downloading Tabler Icons data...");

    let outline_json = download(OUTLINE_URL).expect("Failed to download outline icons");
    let filled_json = download(FILLED_URL).expect("Failed to download filled icons");
    let icons_meta_json = download(ICONS_JSON_URL).expect("Failed to download icons metadata");

    // Parse JSON using flexible Value type
    let outline: BTreeMap<String, Value> =
        serde_json::from_str(&outline_json).expect("Failed to parse outline JSON");
    let filled: BTreeMap<String, Value> =
        serde_json::from_str(&filled_json).expect("Failed to parse filled JSON");
    let icons_meta: BTreeMap<String, Value> =
        serde_json::from_str(&icons_meta_json).expect("Failed to parse icons metadata JSON");

    eprintln!(
        "Found {} outline icons, {} filled icons",
        outline.len(),
        filled.len()
    );

    // Collect all unique icon names with their path data
    // Structure: icon_name -> (outline_paths, filled_paths)
    let mut all_icons: BTreeMap<String, IconPaths> = BTreeMap::new();

    for (name, elements) in &outline {
        if let Some(paths) = extract_paths(elements) {
            all_icons.entry(name.clone()).or_insert((None, None)).0 = Some(paths);
        }
    }

    for (name, elements) in &filled {
        if let Some(paths) = extract_paths(elements) {
            all_icons.entry(name.clone()).or_insert((None, None)).1 = Some(paths);
        }
    }

    // Generate Rust code
    let mut output = String::new();

    // Header
    output.push_str("// This file is auto-generated by build.rs\n");
    output.push_str("// Do not edit manually!\n");
    output.push_str("// Source: https://tabler.io/icons (MIT License)\n\n");

    // Generate enum
    output.push_str("/// Tabler Icon identifier.\n");
    output.push_str("/// \n");
    output.push_str("/// Contains 5000+ icons from [Tabler Icons](https://tabler.io/icons).\n");
    output.push_str("/// Icons are available in Outline and Filled styles.\n");
    output.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    output.push_str("#[non_exhaustive]\n");
    output.push_str("pub enum TablerIcon {\n");

    for name in all_icons.keys() {
        let variant = to_variant_name(name);
        let category = icons_meta
            .get(name)
            .and_then(|v| v.get("category"))
            .and_then(|v| v.as_str())
            .unwrap_or("Unknown");
        output.push_str(&format!("    /// Category: {}\n", category));
        output.push_str(&format!("    {},\n", variant));
    }

    output.push_str("}\n\n");

    // Generate icon count constant
    output.push_str(&format!(
        "/// Total number of unique icons available.\n\
         pub const ICON_COUNT: usize = {};\n\n",
        all_icons.len()
    ));

    // Generate style enum
    output.push_str("/// Icon style variant.\n");
    output.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\n");
    output.push_str("pub enum TablerIconStyle {\n");
    output.push_str("    /// Stroke-based outline style (default).\n");
    output.push_str("    #[default]\n");
    output.push_str("    Outline,\n");
    output.push_str("    /// Solid filled style.\n");
    output.push_str("    Filled,\n");
    output.push_str("}\n\n");

    // Generate impl block for TablerIcon
    output.push_str("impl TablerIcon {\n");

    // name() method
    output.push_str("    /// Returns the kebab-case name of the icon.\n");
    output.push_str("    pub const fn name(&self) -> &'static str {\n");
    output.push_str("        match self {\n");
    for name in all_icons.keys() {
        let variant = to_variant_name(name);
        output.push_str(&format!(
            "            TablerIcon::{} => \"{}\",\n",
            variant, name
        ));
    }
    output.push_str("        }\n");
    output.push_str("    }\n\n");

    // has_filled() method
    output.push_str("    /// Returns true if this icon has a filled variant.\n");
    output.push_str("    pub const fn has_filled(&self) -> bool {\n");
    let filled_variants: Vec<String> = all_icons
        .iter()
        .filter(|(_, (_, filled))| filled.is_some())
        .map(|(name, _)| format!("TablerIcon::{}", to_variant_name(name)))
        .collect();
    if filled_variants.is_empty() {
        output.push_str("        false\n");
    } else {
        output.push_str(&format!(
            "        matches!(self, {})\n",
            filled_variants.join("\n            | ")
        ));
    }
    output.push_str("    }\n\n");

    // has_outline() method
    output.push_str("    /// Returns true if this icon has an outline variant.\n");
    output.push_str("    pub const fn has_outline(&self) -> bool {\n");
    let outline_variants: Vec<String> = all_icons
        .iter()
        .filter(|(_, (outline, _))| outline.is_some())
        .map(|(name, _)| format!("TablerIcon::{}", to_variant_name(name)))
        .collect();
    if outline_variants.is_empty() {
        output.push_str("        false\n");
    } else {
        output.push_str(&format!(
            "        matches!(self, {})\n",
            outline_variants.join("\n            | ")
        ));
    }
    output.push_str("    }\n\n");

    // paths() method - returns SVG path data
    output.push_str("    /// Returns the SVG path data for the given style.\n");
    output.push_str("    /// Returns None if the icon doesn't have the requested style.\n");
    output.push_str(
        "    pub fn paths(&self, style: TablerIconStyle) -> Option<&'static [&'static str]> {\n",
    );
    output.push_str("        match style {\n");
    output.push_str("            TablerIconStyle::Outline => self.outline_paths(),\n");
    output.push_str("            TablerIconStyle::Filled => self.filled_paths(),\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");

    // outline_paths() method
    output.push_str("    /// Returns the outline style SVG path data.\n");
    output.push_str("    #[allow(unreachable_patterns)]\n");
    output.push_str("    pub fn outline_paths(&self) -> Option<&'static [&'static str]> {\n");
    output.push_str("        match self {\n");
    for (name, (outline, _)) in &all_icons {
        if let Some(paths) = outline {
            let variant = to_variant_name(name);
            let paths_literal = paths_to_literal(paths);
            output.push_str(&format!(
                "            TablerIcon::{} => Some(&[{}]),\n",
                variant, paths_literal
            ));
        }
    }
    output.push_str("            _ => None,\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");

    // filled_paths() method
    output.push_str("    /// Returns the filled style SVG path data.\n");
    output.push_str("    #[allow(unreachable_patterns)]\n");
    output.push_str("    pub fn filled_paths(&self) -> Option<&'static [&'static str]> {\n");
    output.push_str("        match self {\n");
    for (name, (_, filled)) in &all_icons {
        if let Some(paths) = filled {
            let variant = to_variant_name(name);
            let paths_literal = paths_to_literal(paths);
            output.push_str(&format!(
                "            TablerIcon::{} => Some(&[{}]),\n",
                variant, paths_literal
            ));
        }
    }
    output.push_str("            _ => None,\n");
    output.push_str("        }\n");
    output.push_str("    }\n");

    output.push_str("}\n\n");

    // Generate Display impl
    output.push_str("impl std::fmt::Display for TablerIcon {\n");
    output.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    output.push_str("        write!(f, \"{}\", self.name())\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    // Generate ALL_ICONS array for iteration
    output.push_str("/// Array of all icon variants for iteration.\n");
    output.push_str("pub static ALL_ICONS: &[TablerIcon] = &[\n");
    for name in all_icons.keys() {
        let variant = to_variant_name(name);
        output.push_str(&format!("    TablerIcon::{},\n", variant));
    }
    output.push_str("];\n");

    // Write to file
    let mut file = fs::File::create(&dest_path).expect("Failed to create generated.rs");
    file.write_all(output.as_bytes())
        .expect("Failed to write generated.rs");

    eprintln!("Generated {} icon variants", all_icons.len());
}

/// Extract path data from icon elements.
/// Elements are arrays like: [["path", {"d": "..."}], ["circle", {"cx": 12, ...}], ...]
/// We convert all elements to path "d" strings where possible.
fn extract_paths(elements: &Value) -> Option<Vec<String>> {
    let arr = elements.as_array()?;
    let mut paths = Vec::new();

    for element in arr {
        let Some(element_arr) = element.as_array() else {
            continue;
        };
        if element_arr.len() < 2 {
            continue;
        }

        let Some(element_type) = element_arr[0].as_str() else {
            continue;
        };
        let attrs = &element_arr[1];

        match element_type {
            "path" => {
                if let Some(d) = attrs.get("d").and_then(|v| v.as_str()) {
                    paths.push(d.to_string());
                }
            }
            "circle" => {
                // Convert circle to path
                if let (Some(cx), Some(cy), Some(r)) = (
                    attrs.get("cx").and_then(|v| v.as_f64()),
                    attrs.get("cy").and_then(|v| v.as_f64()),
                    attrs.get("r").and_then(|v| v.as_f64()),
                ) {
                    // Circle as two arcs
                    let d = format!(
                        "M{} {}a{} {} 0 1 0 {} 0a{} {} 0 1 0 {} 0",
                        cx - r,
                        cy,
                        r,
                        r,
                        r * 2.0,
                        r,
                        r,
                        -r * 2.0
                    );
                    paths.push(d);
                }
            }
            "rect" => {
                // Convert rect to path
                if let (Some(x), Some(y), Some(w), Some(h)) = (
                    attrs.get("x").and_then(|v| v.as_f64()),
                    attrs.get("y").and_then(|v| v.as_f64()),
                    attrs.get("width").and_then(|v| v.as_f64()),
                    attrs.get("height").and_then(|v| v.as_f64()),
                ) {
                    let rx = attrs.get("rx").and_then(|v| v.as_f64()).unwrap_or(0.0);
                    if rx > 0.0 {
                        // Rounded rect
                        let d = format!(
                            "M{} {}h{}a{} {} 0 0 1 {} {}v{}a{} {} 0 0 1 {} {}h{}a{} {} 0 0 1 {} {}v{}a{} {} 0 0 1 {} {}z",
                            x + rx,
                            y,
                            w - 2.0 * rx,
                            rx,
                            rx,
                            rx,
                            rx,
                            h - 2.0 * rx,
                            rx,
                            rx,
                            -rx,
                            rx,
                            -(w - 2.0 * rx),
                            rx,
                            rx,
                            -rx,
                            -rx,
                            -(h - 2.0 * rx),
                            rx,
                            rx,
                            rx,
                            -rx
                        );
                        paths.push(d);
                    } else {
                        let d = format!("M{} {}h{}v{}h{}z", x, y, w, h, -w);
                        paths.push(d);
                    }
                }
            }
            "line" => {
                // Convert line to path
                if let (Some(x1), Some(y1), Some(x2), Some(y2)) = (
                    attrs.get("x1").and_then(|v| v.as_f64()),
                    attrs.get("y1").and_then(|v| v.as_f64()),
                    attrs.get("x2").and_then(|v| v.as_f64()),
                    attrs.get("y2").and_then(|v| v.as_f64()),
                ) {
                    let d = format!("M{} {}L{} {}", x1, y1, x2, y2);
                    paths.push(d);
                }
            }
            "polyline" | "polygon" => {
                // Convert polyline/polygon to path
                if let Some(points) = attrs.get("points").and_then(|v| v.as_str()) {
                    let mut d = String::new();
                    for (i, point) in points.split_whitespace().enumerate() {
                        let cmd = if i == 0 { "M" } else { "L" };
                        // Points can be "x,y" or "x y"
                        let point = point.replace(',', " ");
                        d.push_str(&format!("{}{} ", cmd, point));
                    }
                    if element_type == "polygon" {
                        d.push('z');
                    }
                    if !d.is_empty() {
                        paths.push(d.trim().to_string());
                    }
                }
            }
            "ellipse" => {
                // Convert ellipse to path
                if let (Some(cx), Some(cy), Some(rx), Some(ry)) = (
                    attrs.get("cx").and_then(|v| v.as_f64()),
                    attrs.get("cy").and_then(|v| v.as_f64()),
                    attrs.get("rx").and_then(|v| v.as_f64()),
                    attrs.get("ry").and_then(|v| v.as_f64()),
                ) {
                    let d = format!(
                        "M{} {}a{} {} 0 1 0 {} 0a{} {} 0 1 0 {} 0",
                        cx - rx,
                        cy,
                        rx,
                        ry,
                        rx * 2.0,
                        rx,
                        ry,
                        -rx * 2.0
                    );
                    paths.push(d);
                }
            }
            _ => {
                // Unknown element type, skip
            }
        }
    }

    if paths.is_empty() { None } else { Some(paths) }
}

fn download(url: &str) -> Result<String, Box<dyn std::error::Error>> {
    let mut last_err = None;
    for attempt in 1..=3 {
        match ureq::get(url).call() {
            Ok(response) => match response.into_body().read_to_string() {
                Ok(body) => {
                    // Validate it's complete JSON before accepting
                    if serde_json::from_str::<serde_json::Value>(&body).is_ok() {
                        return Ok(body);
                    }
                    let msg = format!(
                        "Attempt {}: truncated response ({} bytes)",
                        attempt,
                        body.len()
                    );
                    eprintln!("{}", msg);
                    last_err = Some(msg);
                }
                Err(e) => {
                    eprintln!("Attempt {}: read error: {}", attempt, e);
                    last_err = Some(e.to_string());
                }
            },
            Err(e) => {
                eprintln!("Attempt {}: request error: {}", attempt, e);
                last_err = Some(e.to_string());
            }
        }
        if attempt < 3 {
            std::thread::sleep(std::time::Duration::from_secs(2));
        }
    }
    Err(format!("Failed after 3 attempts: {}", last_err.unwrap_or_default()).into())
}

fn to_variant_name(name: &str) -> String {
    // Convert kebab-case to UpperCamelCase
    // Handle special cases like numbers at the start
    let camel = name.to_upper_camel_case();

    // If starts with a number, prefix with underscore
    if camel
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        format!("_{}", camel)
    } else {
        camel
    }
}

fn paths_to_literal(paths: &[String]) -> String {
    paths
        .iter()
        .map(|p| format!("r#\"{}\"#", p))
        .collect::<Vec<_>>()
        .join(", ")
}
