[package]
name = "rinch-editor-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Toolbar and control widgets for Rinch rich-text editor"

[dependencies]
rinch-core = { workspace = true }
rinch-editor = { path = "../rinch-editor" }
rinch-widgets = { path = "../rinch-widgets" }
rinch-macros = { workspace = true }
rinch-tabler-icons = { workspace = true }
