// @generated by tools/gen_html_entities.py — do not edit.
//
// Source: https://html.spec.whatwg.org/entities.json
// sha256: d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6
// 2231 references: 2125 names, 106 of which also decode with no `;`.

/// How many names there are.
pub(super) const COUNT: usize = 2125;

/// The longest name, in bytes.
pub(super) const MAX_NAME: usize = 31;

/// The longest name that decodes with no `;`.
pub(super) const MAX_LEGACY: usize = 6;

/// Bit of a [`NAME_ENDS`] entry: the name decodes with no `;`.
pub(super) const LEGACY: u16 = 0x8000;

/// Every name, in byte order, end to end.
pub(super) static NAMES: &str = "\
     AEligAMPAacuteAbreveAcircAcyAfrAgraveAlphaAmacrAndAogonAopfApplyFunctionAringAscrAssignA\
     tildeAumlBackslashBarvBarwedBcyBecauseBernoullisBetaBfrBopfBreveBscrBumpeqCHcyCOPYCacute\
     CapCapitalDifferentialDCayleysCcaronCcedilCcircCconintCdotCedillaCenterDotCfrChiCircleDo\
     tCircleMinusCirclePlusCircleTimesClockwiseContourIntegralCloseCurlyDoubleQuoteCloseCurly\
     QuoteColonColoneCongruentConintContourIntegralCopfCoproductCounterClockwiseContourIntegr\
     alCrossCscrCupCupCapDDDDotrahdDJcyDScyDZcyDaggerDarrDashvDcaronDcyDelDeltaDfrDiacritical\
     AcuteDiacriticalDotDiacriticalDoubleAcuteDiacriticalGraveDiacriticalTildeDiamondDifferen\
     tialDDopfDotDotDotDotEqualDoubleContourIntegralDoubleDotDoubleDownArrowDoubleLeftArrowDo\
     ubleLeftRightArrowDoubleLeftTeeDoubleLongLeftArrowDoubleLongLeftRightArrowDoubleLongRigh\
     tArrowDoubleRightArrowDoubleRightTeeDoubleUpArrowDoubleUpDownArrowDoubleVerticalBarDownA\
     rrowDownArrowBarDownArrowUpArrowDownBreveDownLeftRightVectorDownLeftTeeVectorDownLeftVec\
     torDownLeftVectorBarDownRightTeeVectorDownRightVectorDownRightVectorBarDownTeeDownTeeArr\
     owDownarrowDscrDstrokENGETHEacuteEcaronEcircEcyEdotEfrEgraveElementEmacrEmptySmallSquare\
     EmptyVerySmallSquareEogonEopfEpsilonEqualEqualTildeEquilibriumEscrEsimEtaEumlExistsExpon\
     entialEFcyFfrFilledSmallSquareFilledVerySmallSquareFopfForAllFouriertrfFscrGJcyGTGammaGa\
     mmadGbreveGcedilGcircGcyGdotGfrGgGopfGreaterEqualGreaterEqualLessGreaterFullEqualGreater\
     GreaterGreaterLessGreaterSlantEqualGreaterTildeGscrGtHARDcyHacekHatHcircHfrHilbertSpaceH\
     opfHorizontalLineHscrHstrokHumpDownHumpHumpEqualIEcyIJligIOcyIacuteIcircIcyIdotIfrIgrave\
     ImImacrImaginaryIImpliesIntIntegralIntersectionInvisibleCommaInvisibleTimesIogonIopfIota\
     IscrItildeIukcyIumlJcircJcyJfrJopfJscrJsercyJukcyKHcyKJcyKappaKcedilKcyKfrKopfKscrLJcyLT\
     LacuteLambdaLangLaplacetrfLarrLcaronLcedilLcyLeftAngleBracketLeftArrowLeftArrowBarLeftAr\
     rowRightArrowLeftCeilingLeftDoubleBracketLeftDownTeeVectorLeftDownVectorLeftDownVectorBa\
     rLeftFloorLeftRightArrowLeftRightVectorLeftTeeLeftTeeArrowLeftTeeVectorLeftTriangleLeftT\
     riangleBarLeftTriangleEqualLeftUpDownVectorLeftUpTeeVectorLeftUpVectorLeftUpVectorBarLef\
     tVectorLeftVectorBarLeftarrowLeftrightarrowLessEqualGreaterLessFullEqualLessGreaterLessL\
     essLessSlantEqualLessTildeLfrLlLleftarrowLmidotLongLeftArrowLongLeftRightArrowLongRightA\
     rrowLongleftarrowLongleftrightarrowLongrightarrowLopfLowerLeftArrowLowerRightArrowLscrLs\
     hLstrokLtMapMcyMediumSpaceMellintrfMfrMinusPlusMopfMscrMuNJcyNacuteNcaronNcedilNcyNegati\
     veMediumSpaceNegativeThickSpaceNegativeThinSpaceNegativeVeryThinSpaceNestedGreaterGreate\
     rNestedLessLessNewLineNfrNoBreakNonBreakingSpaceNopfNotNotCongruentNotCupCapNotDoubleVer\
     ticalBarNotElementNotEqualNotEqualTildeNotExistsNotGreaterNotGreaterEqualNotGreaterFullE\
     qualNotGreaterGreaterNotGreaterLessNotGreaterSlantEqualNotGreaterTildeNotHumpDownHumpNot\
     HumpEqualNotLeftTriangleNotLeftTriangleBarNotLeftTriangleEqualNotLessNotLessEqualNotLess\
     GreaterNotLessLessNotLessSlantEqualNotLessTildeNotNestedGreaterGreaterNotNestedLessLessN\
     otPrecedesNotPrecedesEqualNotPrecedesSlantEqualNotReverseElementNotRightTriangleNotRight\
     TriangleBarNotRightTriangleEqualNotSquareSubsetNotSquareSubsetEqualNotSquareSupersetNotS\
     quareSupersetEqualNotSubsetNotSubsetEqualNotSucceedsNotSucceedsEqualNotSucceedsSlantEqua\
     lNotSucceedsTildeNotSupersetNotSupersetEqualNotTildeNotTildeEqualNotTildeFullEqualNotTil\
     deTildeNotVerticalBarNscrNtildeNuOEligOacuteOcircOcyOdblacOfrOgraveOmacrOmegaOmicronOopf\
     OpenCurlyDoubleQuoteOpenCurlyQuoteOrOscrOslashOtildeOtimesOumlOverBarOverBraceOverBracke\
     tOverParenthesisPartialDPcyPfrPhiPiPlusMinusPoincareplanePopfPrPrecedesPrecedesEqualPrec\
     edesSlantEqualPrecedesTildePrimeProductProportionProportionalPscrPsiQUOTQfrQopfQscrRBarr\
     REGRacuteRangRarrRarrtlRcaronRcedilRcyReReverseElementReverseEquilibriumReverseUpEquilib\
     riumRfrRhoRightAngleBracketRightArrowRightArrowBarRightArrowLeftArrowRightCeilingRightDo\
     ubleBracketRightDownTeeVectorRightDownVectorRightDownVectorBarRightFloorRightTeeRightTee\
     ArrowRightTeeVectorRightTriangleRightTriangleBarRightTriangleEqualRightUpDownVectorRight\
     UpTeeVectorRightUpVectorRightUpVectorBarRightVectorRightVectorBarRightarrowRopfRoundImpl\
     iesRrightarrowRscrRshRuleDelayedSHCHcySHcySOFTcySacuteScScaronScedilScircScySfrShortDown\
     ArrowShortLeftArrowShortRightArrowShortUpArrowSigmaSmallCircleSopfSqrtSquareSquareInters\
     ectionSquareSubsetSquareSubsetEqualSquareSupersetSquareSupersetEqualSquareUnionSscrStarS\
     ubSubsetSubsetEqualSucceedsSucceedsEqualSucceedsSlantEqualSucceedsTildeSuchThatSumSupSup\
     ersetSupersetEqualSupsetTHORNTRADETSHcyTScyTabTauTcaronTcedilTcyTfrThereforeThetaThickSp\
     aceThinSpaceTildeTildeEqualTildeFullEqualTildeTildeTopfTripleDotTscrTstrokUacuteUarrUarr\
     ocirUbrcyUbreveUcircUcyUdblacUfrUgraveUmacrUnderBarUnderBraceUnderBracketUnderParenthesi\
     sUnionUnionPlusUogonUopfUpArrowUpArrowBarUpArrowDownArrowUpDownArrowUpEquilibriumUpTeeUp\
     TeeArrowUparrowUpdownarrowUpperLeftArrowUpperRightArrowUpsiUpsilonUringUscrUtildeUumlVDa\
     shVbarVcyVdashVdashlVeeVerbarVertVerticalBarVerticalLineVerticalSeparatorVerticalTildeVe\
     ryThinSpaceVfrVopfVscrVvdashWcircWedgeWfrWopfWscrXfrXiXopfXscrYAcyYIcyYUcyYacuteYcircYcy\
     YfrYopfYscrYumlZHcyZacuteZcaronZcyZdotZeroWidthSpaceZetaZfrZopfZscraacuteabreveacacEacda\
     circacuteacyaeligafafragravealefsymalephalphaamacramalgampandandandanddandslopeandvangan\
     geangleangmsdangmsdaaangmsdabangmsdacangmsdadangmsdaeangmsdafangmsdagangmsdahangrtangrtv\
     bangrtvbdangsphangstangzarraogonaopfapapEapacirapeapidaposapproxapproxeqaringascrastasym\
     pasympeqatildeaumlawconintawintbNotbackcongbackepsilonbackprimebacksimbacksimeqbarveebar\
     wedbarwedgebbrkbbrktbrkbcongbcybdquobecausbecausebemptyvbepsibernoubetabethbetweenbfrbig\
     capbigcircbigcupbigodotbigoplusbigotimesbigsqcupbigstarbigtriangledownbigtriangleupbigup\
     lusbigveebigwedgebkarowblacklozengeblacksquareblacktriangleblacktriangledownblacktriangl\
     eleftblacktrianglerightblankblk12blk14blk34blockbnebnequivbnotbopfbotbottombowtieboxDLbo\
     xDRboxDlboxDrboxHboxHDboxHUboxHdboxHuboxULboxURboxUlboxUrboxVboxVHboxVLboxVRboxVhboxVlbo\
     xVrboxboxboxdLboxdRboxdlboxdrboxhboxhDboxhUboxhdboxhuboxminusboxplusboxtimesboxuLboxuRbo\
     xulboxurboxvboxvHboxvLboxvRboxvhboxvlboxvrbprimebrevebrvbarbscrbsemibsimbsimebsolbsolbbs\
     olhsubbullbulletbumpbumpEbumpebumpeqcacutecapcapandcapbrcupcapcapcapcupcapdotcapscaretca\
     ronccapsccaronccedilccircccupsccupssmcdotcedilcemptyvcentcenterdotcfrchcycheckcheckmarkc\
     hicircirEcirccirceqcirclearrowleftcirclearrowrightcircledRcircledScircledastcircledcircc\
     ircleddashcirecirfnintcirmidcirscirclubsclubsuitcoloncolonecoloneqcommacommatcompcompfnc\
     omplementcomplexescongcongdotconintcopfcoprodcopycopysrcrarrcrosscscrcsubcsubecsupcsupec\
     tdotcudarrlcudarrrcueprcuesccularrcularrpcupcupbrcapcupcapcupcupcupdotcuporcupscurarrcur\
     arrmcurlyeqpreccurlyeqsucccurlyveecurlywedgecurrencurvearrowleftcurvearrowrightcuveecuwe\
     dcwconintcwintcylctydArrdHardaggerdalethdarrdashdashvdbkarowdblacdcarondcyddddaggerddarr\
     ddotseqdegdeltademptyvdfishtdfrdharldharrdiamdiamonddiamondsuitdiamsdiedigammadisindivdi\
     videdivideontimesdivonxdjcydlcorndlcropdollardopfdotdoteqdoteqdotdotminusdotplusdotsquar\
     edoublebarwedgedownarrowdowndownarrowsdownharpoonleftdownharpoonrightdrbkarowdrcorndrcro\
     pdscrdscydsoldstrokdtdotdtridtrifduarrduhardwangledzcydzigrarreDDoteDoteacuteeasterecaro\
     necirecircecolonecyedoteeefDotefregegraveegsegsdotelelintersellelselsdotemacremptyemptys\
     etemptyvemspemsp13emsp14engenspeogoneopfepareparsleplusepsiepsilonepsiveqcirceqcoloneqsi\
     meqslantgtreqslantlessequalsequestequivequivDDeqvparslerDoterarrescresdotesimetaetheumle\
     uroexclexistexpectationexponentialefallingdotseqfcyfemaleffiligffligfflligffrfiligfjligf\
     latflligfltnsfnoffopfforallforkforkvfpartintfrac12frac13frac14frac15frac16frac18frac23fr\
     ac25frac34frac35frac38frac45frac56frac58frac78fraslfrownfscrgEgElgacutegammagammadgapgbr\
     evegcircgcygdotgegelgeqgeqqgeqslantgesgesccgesdotgesdotogesdotolgeslgeslesgfrggggggimelg\
     jcyglglEglagljgnEgnapgnapproxgnegneqgneqqgnsimgopfgravegscrgsimgsimegsimlgtgtccgtcirgtdo\
     tgtlPargtquestgtrapproxgtrarrgtrdotgtreqlessgtreqqlessgtrlessgtrsimgvertneqqgvnEhArrhair\
     sphalfhamilthardcyharrharrcirharrwhbarhcircheartsheartsuithellipherconhfrhksearowhkswaro\
     whoarrhomththookleftarrowhookrightarrowhopfhorbarhscrhslashhstrokhybullhypheniacuteicici\
     rcicyiecyiexcliffifrigraveiiiiiintiiintiinfiniiotaijligimacrimageimaglineimagpartimathim\
     ofimpedinincareinfininfintieinodotintintcalintegersintercalintlarhkintprodiocyiogoniopfi\
     otaiprodiquestiscrisinisinEisindotisinsisinsvisinvititildeiukcyiumljcircjcyjfrjmathjopfj\
     scrjsercyjukcykappakappavkcedilkcykfrkgreenkhcykjcykopfkscrlAarrlArrlAtaillBarrlElEglHar\
     lacutelaemptyvlagranlambdalanglangdlanglelaplaquolarrlarrblarrbfslarrfslarrhklarrlplarrp\
     llarrsimlarrtllatlataillatelateslbarrlbbrklbracelbracklbrkelbrksldlbrkslulcaronlcedillce\
     illcublcyldcaldquoldquorldrdharldrusharldshleleftarrowleftarrowtailleftharpoondownleftha\
     rpoonupleftleftarrowsleftrightarrowleftrightarrowsleftrightharpoonsleftrightsquigarrowle\
     ftthreetimeslegleqleqqleqslantleslescclesdotlesdotolesdotorlesglesgeslessapproxlessdotle\
     sseqgtrlesseqqgtrlessgtrlesssimlfishtlfloorlfrlglgElhardlharulharullhblkljcyllllarrllcor\
     nerllhardlltrilmidotlmoustlmoustachelnElnaplnapproxlnelneqlneqqlnsimloangloarrlobrklongl\
     eftarrowlongleftrightarrowlongmapstolongrightarrowlooparrowleftlooparrowrightloparlopflo\
     pluslotimeslowastlowbarlozlozengelozflparlparltlrarrlrcornerlrharlrhardlrmlrtrilsaquolsc\
     rlshlsimlsimelsimglsqblsquolsquorlstrokltltccltcirltdotlthreeltimesltlarrltquestltrParlt\
     riltrieltriflurdsharluruharlvertneqqlvnEmDDotmacrmalemaltmaltesemapmapstomapstodownmapst\
     oleftmapstoupmarkermcommamcymdashmeasuredanglemfrmhomicromidmidastmidcirmiddotminusminus\
     bminusdminusdumlcpmldrmnplusmodelsmopfmpmscrmstposmumultimapmumapnGgnGtnGtvnLeftarrownLe\
     ftrightarrownLlnLtnLtvnRightarrownVDashnVdashnablanacutenangnapnapEnapidnaposnapproxnatu\
     rnaturalnaturalsnbspnbumpnbumpencapncaronncedilncongncongdotncupncyndashneneArrnearhknea\
     rrnearrownedotnequivnesearnesimnexistnexistsnfrngEngengeqngeqqngeqslantngesngsimngtngtrn\
     hArrnharrnhparninisnisdnivnjcynlArrnlEnlarrnldrnlenleftarrownleftrightarrownleqnleqqnleq\
     slantnlesnlessnlsimnltnltrinltrienmidnopfnotnotinnotinEnotindotnotinvanotinvbnotinvcnotn\
     inotnivanotnivbnotnivcnparnparallelnparslnpartnpolintnprnprcuenprenprecnpreceqnrArrnrarr\
     nrarrcnrarrwnrightarrownrtrinrtrienscnsccuenscenscrnshortmidnshortparallelnsimnsimensime\
     qnsmidnsparnsqsubensqsupensubnsubEnsubensubsetnsubseteqnsubseteqqnsuccnsucceqnsupnsupEns\
     upensupsetnsupseteqnsupseteqqntglntildentlgntriangleleftntrianglelefteqntrianglerightntr\
     ianglerighteqnunumnumeronumspnvDashnvHarrnvapnvdashnvgenvgtnvinfinnvlArrnvlenvltnvltrien\
     vrArrnvrtrienvsimnwArrnwarhknwarrnwarrownwnearoSoacuteoastocirocircocyodashodblacodivodo\
     todsoldoeligofcirofrogonograveogtohbarohmointolarrolcirolcrossolineoltomacromegaomicrono\
     midominusoopfoparoperpoplusororarrordorderorderofordfordmorigoforororslopeorvoscroslasho\
     solotildeotimesotimesasoumlovbarparparaparallelparsimparslpartpcypercntperiodpermilperpp\
     ertenkpfrphiphivphmmatphonepipitchforkpivplanckplanckhplankvplusplusacirplusbpluscirplus\
     doplusdupluseplusmnplussimplustwopmpointintpopfpoundprprEprapprcuepreprecprecapproxprecc\
     urlyeqpreceqprecnapproxprecneqqprecnsimprecsimprimeprimesprnEprnapprnsimprodprofalarprof\
     lineprofsurfpropproptoprsimprurelpscrpsipuncspqfrqintqopfqprimeqscrquaternionsquatintque\
     stquesteqquotrAarrrArrrAtailrBarrrHarraceracuteradicraemptyvrangrangdrangerangleraquorar\
     rrarraprarrbrarrbfsrarrcrarrfsrarrhkrarrlprarrplrarrsimrarrtlrarrwratailratiorationalsrb\
     arrrbbrkrbracerbrackrbrkerbrksldrbrkslurcaronrcedilrceilrcubrcyrdcardldharrdquordquorrds\
     hrealrealinerealpartrealsrectregrfishtrfloorrfrrhardrharurharulrhorhovrightarrowrightarr\
     owtailrightharpoondownrightharpoonuprightleftarrowsrightleftharpoonsrightrightarrowsrigh\
     tsquigarrowrightthreetimesringrisingdotseqrlarrrlharrlmrmoustrmoustachernmidroangroarrro\
     brkroparropfroplusrotimesrparrpargtrppolintrrarrrsaquorscrrshrsqbrsquorsquorrthreertimes\
     rtrirtriertrifrtriltriruluharrxsacutesbquoscscEscapscaronsccuescescedilscircscnEscnapscn\
     simscpolintscsimscysdotsdotbsdoteseArrsearhksearrsearrowsectsemiseswarsetminussetmnsexts\
     frsfrownsharpshchcyshcyshortmidshortparallelshysigmasigmafsigmavsimsimdotsimesimeqsimgsi\
     mgEsimlsimlEsimnesimplussimrarrslarrsmallsetminussmashpsmeparslsmidsmilesmtsmtesmtessoft\
     cysolsolbsolbarsopfspadesspadesuitsparsqcapsqcapssqcupsqcupssqsubsqsubesqsubsetsqsubsete\
     qsqsupsqsupesqsupsetsqsupseteqsqusquaresquarfsqufsrarrsscrssetmnssmilesstarfstarstarfstr\
     aightepsilonstraightphistrnssubsubEsubdotsubesubedotsubmultsubnEsubnesubplussubrarrsubse\
     tsubseteqsubseteqqsubsetneqsubsetneqqsubsimsubsubsubsupsuccsuccapproxsucccurlyeqsucceqsu\
     ccnapproxsuccneqqsuccnsimsuccsimsumsungsupsup1sup2sup3supEsupdotsupdsubsupesupedotsuphso\
     lsuphsubsuplarrsupmultsupnEsupnesupplussupsetsupseteqsupseteqqsupsetneqsupsetneqqsupsims\
     upsubsupsupswArrswarhkswarrswarrowswnwarszligtargettautbrktcarontcediltcytdottelrectfrth\
     ere4thereforethetathetasymthetavthickapproxthicksimthinspthkapthksimthorntildetimestimes\
     btimesbartimesdtinttoeatoptopbottopcirtopftopforktosatprimetradetriangletriangledowntria\
     nglelefttrianglelefteqtriangleqtrianglerighttrianglerighteqtridottrietriminustriplustris\
     btritimetrpeziumtscrtscytshcytstroktwixttwoheadleftarrowtwoheadrightarrowuArruHaruacuteu\
     arrubrcyubreveucircucyudarrudblacudharufishtufrugraveuharluharruhblkulcornulcornerulcrop\
     ultriumacrumluogonuopfuparrowupdownarrowupharpoonleftupharpoonrightuplusupsiupsihupsilon\
     upuparrowsurcornurcornerurcropuringurtriuscrutdotutildeutriutrifuuarruumluwanglevArrvBar\
     vBarvvDashvangrtvarepsilonvarkappavarnothingvarphivarpivarproptovarrvarrhovarsigmavarsub\
     setneqvarsubsetneqqvarsupsetneqvarsupsetneqqvarthetavartriangleleftvartrianglerightvcyvd\
     ashveeveebarveeeqvellipverbarvertvfrvltrivnsubvnsupvopfvpropvrtrivscrvsubnEvsubnevsupnEv\
     supnevzigzagwcircwedbarwedgewedgeqweierpwfrwopfwpwrwreathwscrxcapxcircxcupxdtrixfrxhArrx\
     harrxixlArrxlarrxmapxnisxodotxopfxoplusxotimexrArrxrarrxscrxsqcupxuplusxutrixveexwedgeya\
     cuteyacyycircycyyenyfryicyyopfyscryucyyumlzacutezcaronzcyzdotzeetrfzetazfrzhcyzigrarrzop\
     fzscrzwjzwnj";

/// Where each name ends in [`NAMES`], with [`LEGACY`].
#[rustfmt::skip]
pub(super) static NAME_ENDS: [u16; COUNT] = [
    32773, 32776, 32782, 20, 32793, 28, 31, 32805, 42, 47, 50, 55, 59, 72, 32845, 81, 87, 32861,
    32865, 106, 110, 116, 119, 126, 136, 140, 143, 147, 152, 156, 162, 166, 32938, 176, 179,
    199, 206, 212, 32986, 223, 230, 234, 241, 250, 253, 256, 265, 276, 286, 297, 321, 342, 357,
    362, 368, 377, 383, 398, 402, 411, 442, 447, 451, 454, 460, 462, 470, 474, 478, 482, 488,
    492, 497, 503, 506, 509, 514, 517, 533, 547, 569, 585, 601, 608, 621, 625, 628, 634, 642,
    663, 672, 687, 702, 722, 735, 754, 778, 798, 814, 828, 841, 858, 875, 884, 896, 912, 921,
    940, 957, 971, 988, 1006, 1021, 1039, 1046, 1058, 1067, 1071, 1077, 1080, 33851, 33857,
    1095, 33868, 1103, 1107, 1110, 33884, 1123, 1128, 1144, 1164, 1169, 1173, 1180, 1185, 1195,
    1206, 1210, 1214, 1217, 33989, 1227, 1239, 1242, 1245, 1262, 1283, 1287, 1293, 1303, 1307,
    1311, 34081, 1318, 1324, 1330, 1336, 1341, 1344, 1348, 1351, 1353, 1357, 1369, 1385, 1401,
    1415, 1426, 1443, 1455, 1459, 1461, 1467, 1472, 1475, 1480, 1483, 1495, 1499, 1513, 1517,
    1523, 1535, 1544, 1548, 1553, 1557, 34331, 34336, 1571, 1575, 1578, 34352, 1586, 1591, 1601,
    1608, 1611, 1619, 1631, 1645, 1659, 1664, 1668, 1672, 1676, 1682, 1687, 34459, 1696, 1699,
    1702, 1706, 1710, 1716, 1721, 1725, 1729, 1734, 1740, 1743, 1746, 1750, 1754, 1758, 34528,
    1766, 1772, 1776, 1786, 1790, 1796, 1802, 1805, 1821, 1830, 1842, 1861, 1872, 1889, 1906,
    1920, 1937, 1946, 1960, 1975, 1982, 1994, 2007, 2019, 2034, 2051, 2067, 2082, 2094, 2109,
    2119, 2132, 2141, 2155, 2171, 2184, 2195, 2203, 2217, 2226, 2229, 2231, 2241, 2247, 2260,
    2278, 2292, 2305, 2323, 2337, 2341, 2355, 2370, 2374, 2377, 2383, 2385, 2388, 2391, 2402,
    2411, 2414, 2423, 2427, 2431, 2433, 2437, 2443, 2449, 2455, 2458, 2477, 2495, 2512, 2533,
    2553, 2567, 2574, 2577, 2584, 2600, 2604, 2607, 2619, 2628, 2648, 2658, 2666, 2679, 2688,
    2698, 2713, 2732, 2749, 2763, 2783, 2798, 2813, 2825, 2840, 2858, 2878, 2885, 2897, 2911,
    2922, 2939, 2951, 2974, 2991, 3002, 3018, 3039, 3056, 3072, 3091, 3112, 3127, 3147, 3164,
    3186, 3195, 3209, 3220, 3236, 3257, 3273, 3284, 3300, 3308, 3321, 3338, 3351, 3365, 3369,
    36143, 3377, 3382, 36156, 36161, 3396, 3402, 3405, 36179, 3416, 3421, 3428, 3432, 3452,
    3466, 3468, 3472, 36246, 36252, 3490, 36262, 3501, 3510, 3521, 3536, 3544, 3547, 3550, 3553,
    3555, 3564, 3577, 3581, 3583, 3591, 3604, 3622, 3635, 3640, 3647, 3657, 3669, 3673, 3676,
    36448, 3683, 3687, 3691, 3696, 36467, 3705, 3709, 3713, 3719, 3725, 3731, 3734, 3736, 3750,
    3768, 3788, 3791, 3794, 3811, 3821, 3834, 3853, 3865, 3883, 3901, 3916, 3934, 3944, 3952,
    3965, 3979, 3992, 4008, 4026, 4043, 4059, 4072, 4088, 4099, 4113, 4123, 4127, 4139, 4150,
    4154, 4157, 4168, 4174, 4178, 4184, 4190, 4192, 4198, 4204, 4209, 4212, 4215, 4229, 4243,
    4258, 4270, 4275, 4286, 4290, 4294, 4300, 4318, 4330, 4347, 4361, 4380, 4391, 4395, 4399,
    4402, 4408, 4419, 4427, 4440, 4458, 4471, 4479, 4482, 4485, 4493, 4506, 4512, 37285, 4522,
    4527, 4531, 4534, 4537, 4543, 4549, 4552, 4555, 4564, 4569, 4579, 4588, 4593, 4603, 4617,
    4627, 4631, 4640, 4644, 4650, 37424, 4660, 4668, 4673, 4679, 37452, 4687, 4693, 4696, 37470,
    4707, 4715, 4725, 4737, 4753, 4758, 4767, 4772, 4776, 4783, 4793, 4809, 4820, 4833, 4838,
    4848, 4855, 4866, 4880, 4895, 4899, 4906, 4911, 4915, 4921, 37693, 4930, 4934, 4937, 4942,
    4948, 4951, 4957, 4961, 4972, 4984, 5001, 5014, 5027, 5030, 5034, 5038, 5044, 5049, 5054,
    5057, 5061, 5065, 5068, 5070, 5074, 5078, 5082, 5086, 5090, 37864, 5101, 5104, 5107, 5111,
    5115, 5119, 5123, 5129, 5135, 5138, 5142, 5156, 5160, 5163, 5167, 5171, 37945, 5183, 5185,
    5188, 5191, 37964, 37969, 5204, 37977, 5211, 5214, 37988, 5227, 5232, 5237, 5242, 5247,
    38018, 5253, 5259, 5263, 5271, 5275, 5278, 5282, 5287, 5293, 5301, 5309, 5317, 5325, 5333,
    5341, 5349, 5357, 5362, 5369, 5377, 5383, 5388, 5395, 5400, 5404, 5406, 5409, 5415, 5418,
    5422, 5426, 5432, 5440, 38213, 5449, 5452, 5457, 5464, 38238, 38242, 5482, 5487, 5491, 5499,
    5510, 5519, 5526, 5535, 5541, 5547, 5555, 5559, 5567, 5572, 5575, 5580, 5586, 5593, 5600,
    5605, 5611, 5615, 5619, 5626, 5629, 5635, 5642, 5648, 5655, 5663, 5672, 5680, 5687, 5702,
    5715, 5723, 5729, 5737, 5743, 5755, 5766, 5779, 5796, 5813, 5831, 5836, 5841, 5846, 5851,
    5856, 5859, 5866, 5870, 5874, 5877, 5883, 5889, 5894, 5899, 5904, 5909, 5913, 5918, 5923,
    5928, 5933, 5938, 5943, 5948, 5953, 5957, 5962, 5967, 5972, 5977, 5982, 5987, 5993, 5998,
    6003, 6008, 6013, 6017, 6022, 6027, 6032, 6037, 6045, 6052, 6060, 6065, 6070, 6075, 6080,
    6084, 6089, 6094, 6099, 6104, 6109, 6114, 6120, 6125, 38899, 6135, 6140, 6144, 6149, 6153,
    6158, 6166, 6170, 6176, 6180, 6185, 6190, 6196, 6202, 6205, 6211, 6219, 6225, 6231, 6237,
    6241, 6246, 6251, 6256, 6262, 39036, 6273, 6278, 6285, 6289, 39062, 6301, 39073, 6314, 6317,
    6321, 6326, 6335, 6338, 6341, 6345, 6349, 6355, 6370, 6386, 6394, 6402, 6412, 6423, 6434,
    6438, 6446, 6452, 6459, 6464, 6472, 6477, 6483, 6490, 6495, 6501, 6505, 6511, 6521, 6530,
    6534, 6541, 6547, 6551, 6557, 39329, 6567, 6572, 6577, 6581, 6585, 6590, 6594, 6599, 6604,
    6611, 6618, 6623, 6628, 6634, 6641, 6644, 6652, 6658, 6664, 6670, 6675, 6679, 6685, 6692,
    6703, 6714, 6722, 6732, 39506, 6752, 6767, 6772, 6777, 6785, 6790, 6796, 6800, 6804, 6810,
    6816, 6820, 6824, 6829, 6836, 6841, 6847, 6850, 6852, 6859, 6864, 6871, 39642, 6879, 6886,
    6892, 6895, 6900, 6905, 6909, 6916, 6927, 6932, 6935, 6942, 6947, 6950, 39724, 6969, 6975,
    6979, 6985, 6991, 6997, 7001, 7004, 7009, 7017, 7025, 7032, 7041, 7055, 7064, 7078, 7093,
    7109, 7117, 7123, 7129, 7133, 7137, 7141, 7147, 7152, 7156, 7161, 7166, 7171, 7178, 7182,
    7190, 7195, 7199, 39973, 7211, 7217, 7221, 39994, 7232, 7235, 7239, 7241, 7246, 7249, 7251,
    40025, 7260, 7266, 7268, 7276, 7279, 7282, 7288, 7293, 7298, 7306, 7312, 7316, 7322, 7328,
    7331, 7335, 7340, 7344, 7348, 7354, 7359, 7363, 7370, 7375, 7381, 7388, 7393, 7403, 7414,
    7420, 7426, 7431, 7438, 7446, 7451, 7456, 7460, 7465, 7469, 7472, 40243, 40247, 7483, 7487,
    7492, 7503, 7515, 7528, 7531, 7537, 7543, 7548, 7554, 7557, 7562, 7567, 7571, 7576, 7581,
    7585, 7589, 7595, 7599, 7604, 7612, 40386, 7624, 40398, 7636, 7642, 7648, 7654, 7660, 40434,
    7672, 7678, 7684, 7690, 7696, 7702, 7707, 7712, 7716, 7718, 7721, 7727, 7732, 7738, 7741,
    7747, 7752, 7755, 7759, 7761, 7764, 7767, 7771, 7779, 7782, 7787, 7793, 7800, 7808, 7812,
    7818, 7821, 7823, 7826, 7831, 7835, 7837, 7840, 7843, 7846, 7849, 7853, 7861, 7864, 7868,
    7873, 7878, 7882, 7887, 7891, 7895, 7900, 7905, 40675, 7911, 7916, 7921, 7927, 7934, 7943,
    7949, 7955, 7964, 7974, 7981, 7987, 7996, 8000, 8004, 8010, 8014, 8020, 8026, 8030, 8037,
    8042, 8046, 8051, 8057, 8066, 8072, 8078, 8081, 8089, 8097, 8102, 8108, 8121, 8135, 8139,
    8145, 8149, 8155, 8161, 8167, 8173, 40947, 8181, 40954, 8189, 8193, 40966, 8201, 8204,
    40978, 8212, 8218, 8223, 8229, 8234, 8239, 8244, 8249, 8257, 8265, 8270, 8274, 8279, 8281,
    8287, 8292, 8300, 8306, 8309, 8315, 8323, 8331, 8339, 8346, 8350, 8355, 8359, 8363, 8368,
    41142, 8378, 8382, 8387, 8394, 8399, 8405, 8410, 8412, 8418, 8423, 41195, 8432, 8435, 8438,
    8443, 8447, 8451, 8457, 8462, 8467, 8473, 8479, 8482, 8485, 8491, 8495, 8499, 8503, 8507,
    8512, 8516, 8522, 8527, 8529, 8532, 8536, 8542, 8550, 8556, 8562, 8566, 8571, 8577, 8580,
    41353, 8589, 8594, 8601, 8607, 8613, 8619, 8625, 8632, 8638, 8641, 8647, 8651, 8656, 8661,
    8666, 8672, 8678, 8683, 8690, 8697, 8703, 8709, 8714, 8718, 8721, 8725, 8730, 8736, 8743,
    8751, 8755, 8757, 8766, 8779, 8794, 8807, 8821, 8835, 8850, 8867, 8886, 8900, 8903, 8906,
    8910, 8918, 8921, 8926, 8932, 8939, 8947, 8951, 8957, 8967, 8974, 8983, 8993, 9000, 9007,
    9013, 9019, 9022, 9024, 9027, 9032, 9037, 9043, 9048, 9052, 9054, 9059, 9067, 9073, 9078,
    9084, 9090, 9100, 9103, 9107, 9115, 9118, 9122, 9127, 9132, 9137, 9142, 9147, 9160, 9178,
    9188, 9202, 9215, 9229, 9234, 9238, 9244, 9251, 9257, 9263, 9266, 9273, 9277, 9281, 9287,
    9292, 9300, 9305, 9311, 9314, 9319, 9325, 9329, 9332, 9336, 9341, 9346, 9350, 9355, 9361,
    9367, 42137, 9373, 9378, 9383, 9389, 9395, 9401, 9408, 9414, 9418, 9423, 9428, 9436, 9443,
    9452, 9456, 9461, 42233, 9469, 9473, 9480, 9483, 9489, 9499, 9509, 9517, 9523, 9529, 9532,
    9537, 9550, 9553, 9556, 42329, 9564, 9570, 9576, 42350, 9587, 9593, 9599, 9606, 9610, 9614,
    9620, 9626, 9630, 9632, 9636, 9642, 9644, 9652, 9657, 9660, 9663, 9667, 9677, 9692, 9695,
    9698, 9702, 9713, 9719, 9725, 9730, 9736, 9740, 9743, 9747, 9752, 9757, 9764, 9769, 9776,
    9784, 42556, 9793, 9799, 9803, 9809, 9815, 9820, 9828, 9832, 9835, 9840, 9842, 9847, 9853,
    9858, 9865, 9870, 9876, 9882, 9887, 9893, 9900, 9903, 9906, 9909, 9913, 9918, 9927, 9931,
    9936, 9939, 9943, 9948, 9953, 9958, 9960, 9963, 9967, 9970, 9974, 9979, 9982, 9987, 9991,
    9994, 10004, 10019, 10023, 10028, 10037, 10041, 10046, 10051, 10054, 10059, 10065, 10069,
    10073, 42844, 10081, 10087, 10095, 10102, 10109, 10116, 10121, 10128, 10135, 10142, 10146,
    10155, 10161, 10166, 10173, 10176, 10182, 10186, 10191, 10198, 10203, 10208, 10214, 10220,
    10231, 10236, 10242, 10245, 10251, 10255, 10259, 10268, 10282, 10286, 10291, 10297, 10302,
    10307, 10314, 10321, 10325, 10330, 10335, 10342, 10351, 10361, 10366, 10373, 10377, 10382,
    10387, 10394, 10403, 10413, 10417, 43191, 10427, 10440, 10455, 10469, 10485, 10487, 10490,
    10496, 10501, 10507, 10513, 10517, 10523, 10527, 10531, 10538, 10544, 10548, 10552, 10559,
    10565, 10572, 10577, 10582, 10588, 10593, 10600, 10606, 10608, 43382, 10618, 10622, 43395,
    10630, 10635, 10641, 10645, 10649, 10655, 10660, 10665, 10668, 10672, 43446, 10681, 10686,
    10689, 10693, 10698, 10703, 10710, 10715, 10718, 10723, 10728, 10735, 10739, 10745, 10749,
    10753, 10758, 10763, 10765, 10770, 10773, 10778, 10785, 43557, 43561, 10799, 10803, 10810,
    10813, 10817, 43591, 10827, 43601, 10839, 10847, 43619, 10856, 10859, 43631, 10871, 10877,
    10882, 10886, 10889, 10895, 10901, 10907, 10911, 10918, 10921, 10924, 10928, 10934, 10939,
    10941, 10950, 10953, 10959, 10966, 10972, 10976, 10984, 10989, 10996, 11002, 11008, 11013,
    43787, 11026, 11033, 11035, 11043, 11047, 43820, 11054, 11057, 11061, 11066, 11069, 11073,
    11083, 11094, 11100, 11111, 11119, 11127, 11134, 11139, 11145, 11149, 11154, 11160, 11164,
    11172, 11180, 11188, 11192, 11198, 11203, 11209, 11213, 11216, 11222, 11225, 11229, 11233,
    11239, 11243, 11254, 11261, 11266, 11273, 44045, 11282, 11286, 11292, 11297, 11301, 11305,
    11311, 11316, 11324, 11328, 11333, 11338, 11344, 44117, 11353, 11359, 11364, 11371, 11376,
    11382, 11388, 11394, 11400, 11407, 11413, 11418, 11424, 11429, 11438, 11443, 11448, 11454,
    11460, 11465, 11472, 11479, 11485, 11491, 11496, 11500, 11503, 11507, 11514, 11519, 11525,
    11529, 11533, 11540, 11548, 11553, 11557, 44328, 11566, 11572, 11575, 11580, 11585, 11591,
    11594, 11598, 11608, 11622, 11638, 11652, 11667, 11684, 11700, 11715, 11730, 11734, 11746,
    11751, 11756, 11759, 11765, 11775, 11780, 11785, 11790, 11795, 11800, 11804, 11810, 11817,
    11821, 11827, 11835, 11840, 11846, 11850, 11853, 11857, 11862, 11868, 11874, 11880, 11884,
    11889, 11894, 11902, 11909, 11911, 11917, 11922, 11924, 11927, 11931, 11937, 11942, 11945,
    11951, 11956, 11960, 11965, 11971, 11979, 11984, 11987, 11991, 11996, 12001, 12006, 12012,
    12017, 12024, 44796, 12032, 12038, 12046, 12051, 12055, 12058, 12064, 12069, 12075, 12079,
    12087, 12100, 44871, 12108, 12114, 12120, 12123, 12129, 12133, 12138, 12142, 12147, 12151,
    12156, 12161, 12168, 12175, 12180, 12193, 12199, 12207, 12211, 12216, 12219, 12223, 12228,
    12234, 12237, 12241, 12247, 12251, 12257, 12266, 12270, 12275, 12281, 12286, 12292, 12297,
    12303, 12311, 12321, 12326, 12332, 12340, 12350, 12353, 12359, 12365, 12369, 12374, 12378,
    12384, 12390, 12396, 12400, 12405, 12420, 12431, 12436, 12439, 12443, 12449, 12453, 12460,
    12467, 12472, 12477, 12484, 12491, 12497, 12505, 12514, 12523, 12533, 12539, 12545, 12551,
    12555, 12565, 12576, 12582, 12593, 12601, 12609, 12616, 12619, 12623, 12626, 45398, 45402,
    45406, 12642, 12648, 12655, 12659, 12666, 12673, 12680, 12687, 12694, 12699, 12704, 12711,
    12717, 12725, 12734, 12743, 12753, 12759, 12765, 12771, 12776, 12782, 12787, 12794, 12800,
    45573, 12811, 12814, 12818, 12824, 12830, 12833, 12837, 12843, 12846, 12852, 12861, 12866,
    12874, 12880, 12891, 12899, 12905, 12910, 12916, 45689, 12926, 45699, 12937, 12945, 12951,
    12955, 12959, 12962, 12968, 12974, 12978, 12985, 12989, 12995, 13000, 13008, 13020, 13032,
    13046, 13055, 13068, 13083, 13089, 13093, 13101, 13108, 13113, 13120, 13128, 13132, 13136,
    13141, 13147, 13152, 13168, 13185, 13189, 13193, 45967, 13203, 13208, 13214, 45987, 13222,
    13227, 13233, 13238, 13244, 13247, 46021, 13258, 13263, 13268, 13274, 13282, 13288, 13293,
    13298, 46069, 13306, 13310, 13317, 13328, 13341, 13355, 13360, 13364, 13369, 13376, 13386,
    13392, 13400, 13406, 13411, 13416, 13420, 13425, 13431, 13435, 13440, 13445, 46217, 13456,
    13460, 13464, 13469, 13474, 13480, 13490, 13498, 13508, 13514, 13519, 13528, 13532, 13538,
    13546, 13558, 13571, 13583, 13596, 13604, 13619, 13635, 13638, 13643, 13646, 13652, 13657,
    13663, 13669, 13673, 13676, 13681, 13686, 13691, 13695, 13700, 13705, 13709, 13715, 13721,
    13727, 13733, 13740, 13745, 13751, 13756, 13762, 13768, 13771, 13775, 13777, 13779, 13785,
    13789, 13793, 13798, 13802, 13807, 13810, 13815, 13820, 13822, 13827, 13832, 13836, 13840,
    13845, 13849, 13855, 13861, 13866, 13871, 13875, 13881, 13887, 13892, 13896, 13902, 46676,
    13912, 13917, 13920, 46691, 13926, 13930, 13934, 13938, 13942, 46714, 13952, 13958, 13961,
    13965, 13971, 13975, 13978, 13982, 13989, 13993, 13997, 14000, 14004,
];

/// What each name stands for (one or two characters), end to end.
pub(super) static VALUES: &str = "\
     \u{c6}\u{26}\u{c1}\u{102}\u{c2}\u{410}\u{1d504}\u{c0}\u{391}\u{100}\u{2a53}\u{104}\
     \u{1d538}\u{2061}\u{c5}\u{1d49c}\u{2254}\u{c3}\u{c4}\u{2216}\u{2ae7}\u{2306}\u{411}\
     \u{2235}\u{212c}\u{392}\u{1d505}\u{1d539}\u{2d8}\u{212c}\u{224e}\u{427}\u{a9}\u{106}\
     \u{22d2}\u{2145}\u{212d}\u{10c}\u{c7}\u{108}\u{2230}\u{10a}\u{b8}\u{b7}\u{212d}\u{3a7}\
     \u{2299}\u{2296}\u{2295}\u{2297}\u{2232}\u{201d}\u{2019}\u{2237}\u{2a74}\u{2261}\u{222f}\
     \u{222e}\u{2102}\u{2210}\u{2233}\u{2a2f}\u{1d49e}\u{22d3}\u{224d}\u{2145}\u{2911}\u{402}\
     \u{405}\u{40f}\u{2021}\u{21a1}\u{2ae4}\u{10e}\u{414}\u{2207}\u{394}\u{1d507}\u{b4}\
     \u{2d9}\u{2dd}\u{60}\u{2dc}\u{22c4}\u{2146}\u{1d53b}\u{a8}\u{20dc}\u{2250}\u{222f}\u{a8}\
     \u{21d3}\u{21d0}\u{21d4}\u{2ae4}\u{27f8}\u{27fa}\u{27f9}\u{21d2}\u{22a8}\u{21d1}\u{21d5}\
     \u{2225}\u{2193}\u{2913}\u{21f5}\u{311}\u{2950}\u{295e}\u{21bd}\u{2956}\u{295f}\u{21c1}\
     \u{2957}\u{22a4}\u{21a7}\u{21d3}\u{1d49f}\u{110}\u{14a}\u{d0}\u{c9}\u{11a}\u{ca}\u{42d}\
     \u{116}\u{1d508}\u{c8}\u{2208}\u{112}\u{25fb}\u{25ab}\u{118}\u{1d53c}\u{395}\u{2a75}\
     \u{2242}\u{21cc}\u{2130}\u{2a73}\u{397}\u{cb}\u{2203}\u{2147}\u{424}\u{1d509}\u{25fc}\
     \u{25aa}\u{1d53d}\u{2200}\u{2131}\u{2131}\u{403}\u{3e}\u{393}\u{3dc}\u{11e}\u{122}\
     \u{11c}\u{413}\u{120}\u{1d50a}\u{22d9}\u{1d53e}\u{2265}\u{22db}\u{2267}\u{2aa2}\u{2277}\
     \u{2a7e}\u{2273}\u{1d4a2}\u{226b}\u{42a}\u{2c7}\u{5e}\u{124}\u{210c}\u{210b}\u{210d}\
     \u{2500}\u{210b}\u{126}\u{224e}\u{224f}\u{415}\u{132}\u{401}\u{cd}\u{ce}\u{418}\u{130}\
     \u{2111}\u{cc}\u{2111}\u{12a}\u{2148}\u{21d2}\u{222c}\u{222b}\u{22c2}\u{2063}\u{2062}\
     \u{12e}\u{1d540}\u{399}\u{2110}\u{128}\u{406}\u{cf}\u{134}\u{419}\u{1d50d}\u{1d541}\
     \u{1d4a5}\u{408}\u{404}\u{425}\u{40c}\u{39a}\u{136}\u{41a}\u{1d50e}\u{1d542}\u{1d4a6}\
     \u{409}\u{3c}\u{139}\u{39b}\u{27ea}\u{2112}\u{219e}\u{13d}\u{13b}\u{41b}\u{27e8}\u{2190}\
     \u{21e4}\u{21c6}\u{2308}\u{27e6}\u{2961}\u{21c3}\u{2959}\u{230a}\u{2194}\u{294e}\u{22a3}\
     \u{21a4}\u{295a}\u{22b2}\u{29cf}\u{22b4}\u{2951}\u{2960}\u{21bf}\u{2958}\u{21bc}\u{2952}\
     \u{21d0}\u{21d4}\u{22da}\u{2266}\u{2276}\u{2aa1}\u{2a7d}\u{2272}\u{1d50f}\u{22d8}\
     \u{21da}\u{13f}\u{27f5}\u{27f7}\u{27f6}\u{27f8}\u{27fa}\u{27f9}\u{1d543}\u{2199}\u{2198}\
     \u{2112}\u{21b0}\u{141}\u{226a}\u{2905}\u{41c}\u{205f}\u{2133}\u{1d510}\u{2213}\u{1d544}\
     \u{2133}\u{39c}\u{40a}\u{143}\u{147}\u{145}\u{41d}\u{200b}\u{200b}\u{200b}\u{200b}\
     \u{226b}\u{226a}\u{a}\u{1d511}\u{2060}\u{a0}\u{2115}\u{2aec}\u{2262}\u{226d}\u{2226}\
     \u{2209}\u{2260}\u{2242}\u{338}\u{2204}\u{226f}\u{2271}\u{2267}\u{338}\u{226b}\u{338}\
     \u{2279}\u{2a7e}\u{338}\u{2275}\u{224e}\u{338}\u{224f}\u{338}\u{22ea}\u{29cf}\u{338}\
     \u{22ec}\u{226e}\u{2270}\u{2278}\u{226a}\u{338}\u{2a7d}\u{338}\u{2274}\u{2aa2}\u{338}\
     \u{2aa1}\u{338}\u{2280}\u{2aaf}\u{338}\u{22e0}\u{220c}\u{22eb}\u{29d0}\u{338}\u{22ed}\
     \u{228f}\u{338}\u{22e2}\u{2290}\u{338}\u{22e3}\u{2282}\u{20d2}\u{2288}\u{2281}\u{2ab0}\
     \u{338}\u{22e1}\u{227f}\u{338}\u{2283}\u{20d2}\u{2289}\u{2241}\u{2244}\u{2247}\u{2249}\
     \u{2224}\u{1d4a9}\u{d1}\u{39d}\u{152}\u{d3}\u{d4}\u{41e}\u{150}\u{1d512}\u{d2}\u{14c}\
     \u{3a9}\u{39f}\u{1d546}\u{201c}\u{2018}\u{2a54}\u{1d4aa}\u{d8}\u{d5}\u{2a37}\u{d6}\
     \u{203e}\u{23de}\u{23b4}\u{23dc}\u{2202}\u{41f}\u{1d513}\u{3a6}\u{3a0}\u{b1}\u{210c}\
     \u{2119}\u{2abb}\u{227a}\u{2aaf}\u{227c}\u{227e}\u{2033}\u{220f}\u{2237}\u{221d}\
     \u{1d4ab}\u{3a8}\u{22}\u{1d514}\u{211a}\u{1d4ac}\u{2910}\u{ae}\u{154}\u{27eb}\u{21a0}\
     \u{2916}\u{158}\u{156}\u{420}\u{211c}\u{220b}\u{21cb}\u{296f}\u{211c}\u{3a1}\u{27e9}\
     \u{2192}\u{21e5}\u{21c4}\u{2309}\u{27e7}\u{295d}\u{21c2}\u{2955}\u{230b}\u{22a2}\u{21a6}\
     \u{295b}\u{22b3}\u{29d0}\u{22b5}\u{294f}\u{295c}\u{21be}\u{2954}\u{21c0}\u{2953}\u{21d2}\
     \u{211d}\u{2970}\u{21db}\u{211b}\u{21b1}\u{29f4}\u{429}\u{428}\u{42c}\u{15a}\u{2abc}\
     \u{160}\u{15e}\u{15c}\u{421}\u{1d516}\u{2193}\u{2190}\u{2192}\u{2191}\u{3a3}\u{2218}\
     \u{1d54a}\u{221a}\u{25a1}\u{2293}\u{228f}\u{2291}\u{2290}\u{2292}\u{2294}\u{1d4ae}\
     \u{22c6}\u{22d0}\u{22d0}\u{2286}\u{227b}\u{2ab0}\u{227d}\u{227f}\u{220b}\u{2211}\u{22d1}\
     \u{2283}\u{2287}\u{22d1}\u{de}\u{2122}\u{40b}\u{426}\u{9}\u{3a4}\u{164}\u{162}\u{422}\
     \u{1d517}\u{2234}\u{398}\u{205f}\u{200a}\u{2009}\u{223c}\u{2243}\u{2245}\u{2248}\
     \u{1d54b}\u{20db}\u{1d4af}\u{166}\u{da}\u{219f}\u{2949}\u{40e}\u{16c}\u{db}\u{423}\
     \u{170}\u{1d518}\u{d9}\u{16a}\u{5f}\u{23df}\u{23b5}\u{23dd}\u{22c3}\u{228e}\u{172}\
     \u{1d54c}\u{2191}\u{2912}\u{21c5}\u{2195}\u{296e}\u{22a5}\u{21a5}\u{21d1}\u{21d5}\
     \u{2196}\u{2197}\u{3d2}\u{3a5}\u{16e}\u{1d4b0}\u{168}\u{dc}\u{22ab}\u{2aeb}\u{412}\
     \u{22a9}\u{2ae6}\u{22c1}\u{2016}\u{2016}\u{2223}\u{7c}\u{2758}\u{2240}\u{200a}\u{1d519}\
     \u{1d54d}\u{1d4b1}\u{22aa}\u{174}\u{22c0}\u{1d51a}\u{1d54e}\u{1d4b2}\u{1d51b}\u{39e}\
     \u{1d54f}\u{1d4b3}\u{42f}\u{407}\u{42e}\u{dd}\u{176}\u{42b}\u{1d51c}\u{1d550}\u{1d4b4}\
     \u{178}\u{416}\u{179}\u{17d}\u{417}\u{17b}\u{200b}\u{396}\u{2128}\u{2124}\u{1d4b5}\u{e1}\
     \u{103}\u{223e}\u{223e}\u{333}\u{223f}\u{e2}\u{b4}\u{430}\u{e6}\u{2061}\u{1d51e}\u{e0}\
     \u{2135}\u{2135}\u{3b1}\u{101}\u{2a3f}\u{26}\u{2227}\u{2a55}\u{2a5c}\u{2a58}\u{2a5a}\
     \u{2220}\u{29a4}\u{2220}\u{2221}\u{29a8}\u{29a9}\u{29aa}\u{29ab}\u{29ac}\u{29ad}\u{29ae}\
     \u{29af}\u{221f}\u{22be}\u{299d}\u{2222}\u{c5}\u{237c}\u{105}\u{1d552}\u{2248}\u{2a70}\
     \u{2a6f}\u{224a}\u{224b}\u{27}\u{2248}\u{224a}\u{e5}\u{1d4b6}\u{2a}\u{2248}\u{224d}\
     \u{e3}\u{e4}\u{2233}\u{2a11}\u{2aed}\u{224c}\u{3f6}\u{2035}\u{223d}\u{22cd}\u{22bd}\
     \u{2305}\u{2305}\u{23b5}\u{23b6}\u{224c}\u{431}\u{201e}\u{2235}\u{2235}\u{29b0}\u{3f6}\
     \u{212c}\u{3b2}\u{2136}\u{226c}\u{1d51f}\u{22c2}\u{25ef}\u{22c3}\u{2a00}\u{2a01}\u{2a02}\
     \u{2a06}\u{2605}\u{25bd}\u{25b3}\u{2a04}\u{22c1}\u{22c0}\u{290d}\u{29eb}\u{25aa}\u{25b4}\
     \u{25be}\u{25c2}\u{25b8}\u{2423}\u{2592}\u{2591}\u{2593}\u{2588}\u{3d}\u{20e5}\u{2261}\
     \u{20e5}\u{2310}\u{1d553}\u{22a5}\u{22a5}\u{22c8}\u{2557}\u{2554}\u{2556}\u{2553}\
     \u{2550}\u{2566}\u{2569}\u{2564}\u{2567}\u{255d}\u{255a}\u{255c}\u{2559}\u{2551}\u{256c}\
     \u{2563}\u{2560}\u{256b}\u{2562}\u{255f}\u{29c9}\u{2555}\u{2552}\u{2510}\u{250c}\u{2500}\
     \u{2565}\u{2568}\u{252c}\u{2534}\u{229f}\u{229e}\u{22a0}\u{255b}\u{2558}\u{2518}\u{2514}\
     \u{2502}\u{256a}\u{2561}\u{255e}\u{253c}\u{2524}\u{251c}\u{2035}\u{2d8}\u{a6}\u{1d4b7}\
     \u{204f}\u{223d}\u{22cd}\u{5c}\u{29c5}\u{27c8}\u{2022}\u{2022}\u{224e}\u{2aae}\u{224f}\
     \u{224f}\u{107}\u{2229}\u{2a44}\u{2a49}\u{2a4b}\u{2a47}\u{2a40}\u{2229}\u{fe00}\u{2041}\
     \u{2c7}\u{2a4d}\u{10d}\u{e7}\u{109}\u{2a4c}\u{2a50}\u{10b}\u{b8}\u{29b2}\u{a2}\u{b7}\
     \u{1d520}\u{447}\u{2713}\u{2713}\u{3c7}\u{25cb}\u{29c3}\u{2c6}\u{2257}\u{21ba}\u{21bb}\
     \u{ae}\u{24c8}\u{229b}\u{229a}\u{229d}\u{2257}\u{2a10}\u{2aef}\u{29c2}\u{2663}\u{2663}\
     \u{3a}\u{2254}\u{2254}\u{2c}\u{40}\u{2201}\u{2218}\u{2201}\u{2102}\u{2245}\u{2a6d}\
     \u{222e}\u{1d554}\u{2210}\u{a9}\u{2117}\u{21b5}\u{2717}\u{1d4b8}\u{2acf}\u{2ad1}\u{2ad0}\
     \u{2ad2}\u{22ef}\u{2938}\u{2935}\u{22de}\u{22df}\u{21b6}\u{293d}\u{222a}\u{2a48}\u{2a46}\
     \u{2a4a}\u{228d}\u{2a45}\u{222a}\u{fe00}\u{21b7}\u{293c}\u{22de}\u{22df}\u{22ce}\u{22cf}\
     \u{a4}\u{21b6}\u{21b7}\u{22ce}\u{22cf}\u{2232}\u{2231}\u{232d}\u{21d3}\u{2965}\u{2020}\
     \u{2138}\u{2193}\u{2010}\u{22a3}\u{290f}\u{2dd}\u{10f}\u{434}\u{2146}\u{2021}\u{21ca}\
     \u{2a77}\u{b0}\u{3b4}\u{29b1}\u{297f}\u{1d521}\u{21c3}\u{21c2}\u{22c4}\u{22c4}\u{2666}\
     \u{2666}\u{a8}\u{3dd}\u{22f2}\u{f7}\u{f7}\u{22c7}\u{22c7}\u{452}\u{231e}\u{230d}\u{24}\
     \u{1d555}\u{2d9}\u{2250}\u{2251}\u{2238}\u{2214}\u{22a1}\u{2306}\u{2193}\u{21ca}\u{21c3}\
     \u{21c2}\u{2910}\u{231f}\u{230c}\u{1d4b9}\u{455}\u{29f6}\u{111}\u{22f1}\u{25bf}\u{25be}\
     \u{21f5}\u{296f}\u{29a6}\u{45f}\u{27ff}\u{2a77}\u{2251}\u{e9}\u{2a6e}\u{11b}\u{2256}\
     \u{ea}\u{2255}\u{44d}\u{117}\u{2147}\u{2252}\u{1d522}\u{2a9a}\u{e8}\u{2a96}\u{2a98}\
     \u{2a99}\u{23e7}\u{2113}\u{2a95}\u{2a97}\u{113}\u{2205}\u{2205}\u{2205}\u{2003}\u{2004}\
     \u{2005}\u{14b}\u{2002}\u{119}\u{1d556}\u{22d5}\u{29e3}\u{2a71}\u{3b5}\u{3b5}\u{3f5}\
     \u{2256}\u{2255}\u{2242}\u{2a96}\u{2a95}\u{3d}\u{225f}\u{2261}\u{2a78}\u{29e5}\u{2253}\
     \u{2971}\u{212f}\u{2250}\u{2242}\u{3b7}\u{f0}\u{eb}\u{20ac}\u{21}\u{2203}\u{2130}\
     \u{2147}\u{2252}\u{444}\u{2640}\u{fb03}\u{fb00}\u{fb04}\u{1d523}\u{fb01}\u{66}\u{6a}\
     \u{266d}\u{fb02}\u{25b1}\u{192}\u{1d557}\u{2200}\u{22d4}\u{2ad9}\u{2a0d}\u{bd}\u{2153}\
     \u{bc}\u{2155}\u{2159}\u{215b}\u{2154}\u{2156}\u{be}\u{2157}\u{215c}\u{2158}\u{215a}\
     \u{215d}\u{215e}\u{2044}\u{2322}\u{1d4bb}\u{2267}\u{2a8c}\u{1f5}\u{3b3}\u{3dd}\u{2a86}\
     \u{11f}\u{11d}\u{433}\u{121}\u{2265}\u{22db}\u{2265}\u{2267}\u{2a7e}\u{2a7e}\u{2aa9}\
     \u{2a80}\u{2a82}\u{2a84}\u{22db}\u{fe00}\u{2a94}\u{1d524}\u{226b}\u{22d9}\u{2137}\u{453}\
     \u{2277}\u{2a92}\u{2aa5}\u{2aa4}\u{2269}\u{2a8a}\u{2a8a}\u{2a88}\u{2a88}\u{2269}\u{22e7}\
     \u{1d558}\u{60}\u{210a}\u{2273}\u{2a8e}\u{2a90}\u{3e}\u{2aa7}\u{2a7a}\u{22d7}\u{2995}\
     \u{2a7c}\u{2a86}\u{2978}\u{22d7}\u{22db}\u{2a8c}\u{2277}\u{2273}\u{2269}\u{fe00}\u{2269}\
     \u{fe00}\u{21d4}\u{200a}\u{bd}\u{210b}\u{44a}\u{2194}\u{2948}\u{21ad}\u{210f}\u{125}\
     \u{2665}\u{2665}\u{2026}\u{22b9}\u{1d525}\u{2925}\u{2926}\u{21ff}\u{223b}\u{21a9}\
     \u{21aa}\u{1d559}\u{2015}\u{1d4bd}\u{210f}\u{127}\u{2043}\u{2010}\u{ed}\u{2063}\u{ee}\
     \u{438}\u{435}\u{a1}\u{21d4}\u{1d526}\u{ec}\u{2148}\u{2a0c}\u{222d}\u{29dc}\u{2129}\
     \u{133}\u{12b}\u{2111}\u{2110}\u{2111}\u{131}\u{22b7}\u{1b5}\u{2208}\u{2105}\u{221e}\
     \u{29dd}\u{131}\u{222b}\u{22ba}\u{2124}\u{22ba}\u{2a17}\u{2a3c}\u{451}\u{12f}\u{1d55a}\
     \u{3b9}\u{2a3c}\u{bf}\u{1d4be}\u{2208}\u{22f9}\u{22f5}\u{22f4}\u{22f3}\u{2208}\u{2062}\
     \u{129}\u{456}\u{ef}\u{135}\u{439}\u{1d527}\u{237}\u{1d55b}\u{1d4bf}\u{458}\u{454}\
     \u{3ba}\u{3f0}\u{137}\u{43a}\u{1d528}\u{138}\u{445}\u{45c}\u{1d55c}\u{1d4c0}\u{21da}\
     \u{21d0}\u{291b}\u{290e}\u{2266}\u{2a8b}\u{2962}\u{13a}\u{29b4}\u{2112}\u{3bb}\u{27e8}\
     \u{2991}\u{27e8}\u{2a85}\u{ab}\u{2190}\u{21e4}\u{291f}\u{291d}\u{21a9}\u{21ab}\u{2939}\
     \u{2973}\u{21a2}\u{2aab}\u{2919}\u{2aad}\u{2aad}\u{fe00}\u{290c}\u{2772}\u{7b}\u{5b}\
     \u{298b}\u{298f}\u{298d}\u{13e}\u{13c}\u{2308}\u{7b}\u{43b}\u{2936}\u{201c}\u{201e}\
     \u{2967}\u{294b}\u{21b2}\u{2264}\u{2190}\u{21a2}\u{21bd}\u{21bc}\u{21c7}\u{2194}\u{21c6}\
     \u{21cb}\u{21ad}\u{22cb}\u{22da}\u{2264}\u{2266}\u{2a7d}\u{2a7d}\u{2aa8}\u{2a7f}\u{2a81}\
     \u{2a83}\u{22da}\u{fe00}\u{2a93}\u{2a85}\u{22d6}\u{22da}\u{2a8b}\u{2276}\u{2272}\u{297c}\
     \u{230a}\u{1d529}\u{2276}\u{2a91}\u{21bd}\u{21bc}\u{296a}\u{2584}\u{459}\u{226a}\u{21c7}\
     \u{231e}\u{296b}\u{25fa}\u{140}\u{23b0}\u{23b0}\u{2268}\u{2a89}\u{2a89}\u{2a87}\u{2a87}\
     \u{2268}\u{22e6}\u{27ec}\u{21fd}\u{27e6}\u{27f5}\u{27f7}\u{27fc}\u{27f6}\u{21ab}\u{21ac}\
     \u{2985}\u{1d55d}\u{2a2d}\u{2a34}\u{2217}\u{5f}\u{25ca}\u{25ca}\u{29eb}\u{28}\u{2993}\
     \u{21c6}\u{231f}\u{21cb}\u{296d}\u{200e}\u{22bf}\u{2039}\u{1d4c1}\u{21b0}\u{2272}\
     \u{2a8d}\u{2a8f}\u{5b}\u{2018}\u{201a}\u{142}\u{3c}\u{2aa6}\u{2a79}\u{22d6}\u{22cb}\
     \u{22c9}\u{2976}\u{2a7b}\u{2996}\u{25c3}\u{22b4}\u{25c2}\u{294a}\u{2966}\u{2268}\u{fe00}\
     \u{2268}\u{fe00}\u{223a}\u{af}\u{2642}\u{2720}\u{2720}\u{21a6}\u{21a6}\u{21a7}\u{21a4}\
     \u{21a5}\u{25ae}\u{2a29}\u{43c}\u{2014}\u{2221}\u{1d52a}\u{2127}\u{b5}\u{2223}\u{2a}\
     \u{2af0}\u{b7}\u{2212}\u{229f}\u{2238}\u{2a2a}\u{2adb}\u{2026}\u{2213}\u{22a7}\u{1d55e}\
     \u{2213}\u{1d4c2}\u{223e}\u{3bc}\u{22b8}\u{22b8}\u{22d9}\u{338}\u{226b}\u{20d2}\u{226b}\
     \u{338}\u{21cd}\u{21ce}\u{22d8}\u{338}\u{226a}\u{20d2}\u{226a}\u{338}\u{21cf}\u{22af}\
     \u{22ae}\u{2207}\u{144}\u{2220}\u{20d2}\u{2249}\u{2a70}\u{338}\u{224b}\u{338}\u{149}\
     \u{2249}\u{266e}\u{266e}\u{2115}\u{a0}\u{224e}\u{338}\u{224f}\u{338}\u{2a43}\u{148}\
     \u{146}\u{2247}\u{2a6d}\u{338}\u{2a42}\u{43d}\u{2013}\u{2260}\u{21d7}\u{2924}\u{2197}\
     \u{2197}\u{2250}\u{338}\u{2262}\u{2928}\u{2242}\u{338}\u{2204}\u{2204}\u{1d52b}\u{2267}\
     \u{338}\u{2271}\u{2271}\u{2267}\u{338}\u{2a7e}\u{338}\u{2a7e}\u{338}\u{2275}\u{226f}\
     \u{226f}\u{21ce}\u{21ae}\u{2af2}\u{220b}\u{22fc}\u{22fa}\u{220b}\u{45a}\u{21cd}\u{2266}\
     \u{338}\u{219a}\u{2025}\u{2270}\u{219a}\u{21ae}\u{2270}\u{2266}\u{338}\u{2a7d}\u{338}\
     \u{2a7d}\u{338}\u{226e}\u{2274}\u{226e}\u{22ea}\u{22ec}\u{2224}\u{1d55f}\u{ac}\u{2209}\
     \u{22f9}\u{338}\u{22f5}\u{338}\u{2209}\u{22f7}\u{22f6}\u{220c}\u{220c}\u{22fe}\u{22fd}\
     \u{2226}\u{2226}\u{2afd}\u{20e5}\u{2202}\u{338}\u{2a14}\u{2280}\u{22e0}\u{2aaf}\u{338}\
     \u{2280}\u{2aaf}\u{338}\u{21cf}\u{219b}\u{2933}\u{338}\u{219d}\u{338}\u{219b}\u{22eb}\
     \u{22ed}\u{2281}\u{22e1}\u{2ab0}\u{338}\u{1d4c3}\u{2224}\u{2226}\u{2241}\u{2244}\u{2244}\
     \u{2224}\u{2226}\u{22e2}\u{22e3}\u{2284}\u{2ac5}\u{338}\u{2288}\u{2282}\u{20d2}\u{2288}\
     \u{2ac5}\u{338}\u{2281}\u{2ab0}\u{338}\u{2285}\u{2ac6}\u{338}\u{2289}\u{2283}\u{20d2}\
     \u{2289}\u{2ac6}\u{338}\u{2279}\u{f1}\u{2278}\u{22ea}\u{22ec}\u{22eb}\u{22ed}\u{3bd}\
     \u{23}\u{2116}\u{2007}\u{22ad}\u{2904}\u{224d}\u{20d2}\u{22ac}\u{2265}\u{20d2}\u{3e}\
     \u{20d2}\u{29de}\u{2902}\u{2264}\u{20d2}\u{3c}\u{20d2}\u{22b4}\u{20d2}\u{2903}\u{22b5}\
     \u{20d2}\u{223c}\u{20d2}\u{21d6}\u{2923}\u{2196}\u{2196}\u{2927}\u{24c8}\u{f3}\u{229b}\
     \u{229a}\u{f4}\u{43e}\u{229d}\u{151}\u{2a38}\u{2299}\u{29bc}\u{153}\u{29bf}\u{1d52c}\
     \u{2db}\u{f2}\u{29c1}\u{29b5}\u{3a9}\u{222e}\u{21ba}\u{29be}\u{29bb}\u{203e}\u{29c0}\
     \u{14d}\u{3c9}\u{3bf}\u{29b6}\u{2296}\u{1d560}\u{29b7}\u{29b9}\u{2295}\u{2228}\u{21bb}\
     \u{2a5d}\u{2134}\u{2134}\u{aa}\u{ba}\u{22b6}\u{2a56}\u{2a57}\u{2a5b}\u{2134}\u{f8}\
     \u{2298}\u{f5}\u{2297}\u{2a36}\u{f6}\u{233d}\u{2225}\u{b6}\u{2225}\u{2af3}\u{2afd}\
     \u{2202}\u{43f}\u{25}\u{2e}\u{2030}\u{22a5}\u{2031}\u{1d52d}\u{3c6}\u{3d5}\u{2133}\
     \u{260e}\u{3c0}\u{22d4}\u{3d6}\u{210f}\u{210e}\u{210f}\u{2b}\u{2a23}\u{229e}\u{2a22}\
     \u{2214}\u{2a25}\u{2a72}\u{b1}\u{2a26}\u{2a27}\u{b1}\u{2a15}\u{1d561}\u{a3}\u{227a}\
     \u{2ab3}\u{2ab7}\u{227c}\u{2aaf}\u{227a}\u{2ab7}\u{227c}\u{2aaf}\u{2ab9}\u{2ab5}\u{22e8}\
     \u{227e}\u{2032}\u{2119}\u{2ab5}\u{2ab9}\u{22e8}\u{220f}\u{232e}\u{2312}\u{2313}\u{221d}\
     \u{221d}\u{227e}\u{22b0}\u{1d4c5}\u{3c8}\u{2008}\u{1d52e}\u{2a0c}\u{1d562}\u{2057}\
     \u{1d4c6}\u{210d}\u{2a16}\u{3f}\u{225f}\u{22}\u{21db}\u{21d2}\u{291c}\u{290f}\u{2964}\
     \u{223d}\u{331}\u{155}\u{221a}\u{29b3}\u{27e9}\u{2992}\u{29a5}\u{27e9}\u{bb}\u{2192}\
     \u{2975}\u{21e5}\u{2920}\u{2933}\u{291e}\u{21aa}\u{21ac}\u{2945}\u{2974}\u{21a3}\u{219d}\
     \u{291a}\u{2236}\u{211a}\u{290d}\u{2773}\u{7d}\u{5d}\u{298c}\u{298e}\u{2990}\u{159}\
     \u{157}\u{2309}\u{7d}\u{440}\u{2937}\u{2969}\u{201d}\u{201d}\u{21b3}\u{211c}\u{211b}\
     \u{211c}\u{211d}\u{25ad}\u{ae}\u{297d}\u{230b}\u{1d52f}\u{21c1}\u{21c0}\u{296c}\u{3c1}\
     \u{3f1}\u{2192}\u{21a3}\u{21c1}\u{21c0}\u{21c4}\u{21cc}\u{21c9}\u{219d}\u{22cc}\u{2da}\
     \u{2253}\u{21c4}\u{21cc}\u{200f}\u{23b1}\u{23b1}\u{2aee}\u{27ed}\u{21fe}\u{27e7}\u{2986}\
     \u{1d563}\u{2a2e}\u{2a35}\u{29}\u{2994}\u{2a12}\u{21c9}\u{203a}\u{1d4c7}\u{21b1}\u{5d}\
     \u{2019}\u{2019}\u{22cc}\u{22ca}\u{25b9}\u{22b5}\u{25b8}\u{29ce}\u{2968}\u{211e}\u{15b}\
     \u{201a}\u{227b}\u{2ab4}\u{2ab8}\u{161}\u{227d}\u{2ab0}\u{15f}\u{15d}\u{2ab6}\u{2aba}\
     \u{22e9}\u{2a13}\u{227f}\u{441}\u{22c5}\u{22a1}\u{2a66}\u{21d8}\u{2925}\u{2198}\u{2198}\
     \u{a7}\u{3b}\u{2929}\u{2216}\u{2216}\u{2736}\u{1d530}\u{2322}\u{266f}\u{449}\u{448}\
     \u{2223}\u{2225}\u{ad}\u{3c3}\u{3c2}\u{3c2}\u{223c}\u{2a6a}\u{2243}\u{2243}\u{2a9e}\
     \u{2aa0}\u{2a9d}\u{2a9f}\u{2246}\u{2a24}\u{2972}\u{2190}\u{2216}\u{2a33}\u{29e4}\u{2223}\
     \u{2323}\u{2aaa}\u{2aac}\u{2aac}\u{fe00}\u{44c}\u{2f}\u{29c4}\u{233f}\u{1d564}\u{2660}\
     \u{2660}\u{2225}\u{2293}\u{2293}\u{fe00}\u{2294}\u{2294}\u{fe00}\u{228f}\u{2291}\u{228f}\
     \u{2291}\u{2290}\u{2292}\u{2290}\u{2292}\u{25a1}\u{25a1}\u{25aa}\u{25aa}\u{2192}\
     \u{1d4c8}\u{2216}\u{2323}\u{22c6}\u{2606}\u{2605}\u{3f5}\u{3d5}\u{af}\u{2282}\u{2ac5}\
     \u{2abd}\u{2286}\u{2ac3}\u{2ac1}\u{2acb}\u{228a}\u{2abf}\u{2979}\u{2282}\u{2286}\u{2ac5}\
     \u{228a}\u{2acb}\u{2ac7}\u{2ad5}\u{2ad3}\u{227b}\u{2ab8}\u{227d}\u{2ab0}\u{2aba}\u{2ab6}\
     \u{22e9}\u{227f}\u{2211}\u{266a}\u{2283}\u{b9}\u{b2}\u{b3}\u{2ac6}\u{2abe}\u{2ad8}\
     \u{2287}\u{2ac4}\u{27c9}\u{2ad7}\u{297b}\u{2ac2}\u{2acc}\u{228b}\u{2ac0}\u{2283}\u{2287}\
     \u{2ac6}\u{228b}\u{2acc}\u{2ac8}\u{2ad4}\u{2ad6}\u{21d9}\u{2926}\u{2199}\u{2199}\u{292a}\
     \u{df}\u{2316}\u{3c4}\u{23b4}\u{165}\u{163}\u{442}\u{20db}\u{2315}\u{1d531}\u{2234}\
     \u{2234}\u{3b8}\u{3d1}\u{3d1}\u{2248}\u{223c}\u{2009}\u{2248}\u{223c}\u{fe}\u{2dc}\u{d7}\
     \u{22a0}\u{2a31}\u{2a30}\u{222d}\u{2928}\u{22a4}\u{2336}\u{2af1}\u{1d565}\u{2ada}\
     \u{2929}\u{2034}\u{2122}\u{25b5}\u{25bf}\u{25c3}\u{22b4}\u{225c}\u{25b9}\u{22b5}\u{25ec}\
     \u{225c}\u{2a3a}\u{2a39}\u{29cd}\u{2a3b}\u{23e2}\u{1d4c9}\u{446}\u{45b}\u{167}\u{226c}\
     \u{219e}\u{21a0}\u{21d1}\u{2963}\u{fa}\u{2191}\u{45e}\u{16d}\u{fb}\u{443}\u{21c5}\u{171}\
     \u{296e}\u{297e}\u{1d532}\u{f9}\u{21bf}\u{21be}\u{2580}\u{231c}\u{231c}\u{230f}\u{25f8}\
     \u{16b}\u{a8}\u{173}\u{1d566}\u{2191}\u{2195}\u{21bf}\u{21be}\u{228e}\u{3c5}\u{3d2}\
     \u{3c5}\u{21c8}\u{231d}\u{231d}\u{230e}\u{16f}\u{25f9}\u{1d4ca}\u{22f0}\u{169}\u{25b5}\
     \u{25b4}\u{21c8}\u{fc}\u{29a7}\u{21d5}\u{2ae8}\u{2ae9}\u{22a8}\u{299c}\u{3f5}\u{3f0}\
     \u{2205}\u{3d5}\u{3d6}\u{221d}\u{2195}\u{3f1}\u{3c2}\u{228a}\u{fe00}\u{2acb}\u{fe00}\
     \u{228b}\u{fe00}\u{2acc}\u{fe00}\u{3d1}\u{22b2}\u{22b3}\u{432}\u{22a2}\u{2228}\u{22bb}\
     \u{225a}\u{22ee}\u{7c}\u{7c}\u{1d533}\u{22b2}\u{2282}\u{20d2}\u{2283}\u{20d2}\u{1d567}\
     \u{221d}\u{22b3}\u{1d4cb}\u{2acb}\u{fe00}\u{228a}\u{fe00}\u{2acc}\u{fe00}\u{228b}\
     \u{fe00}\u{299a}\u{175}\u{2a5f}\u{2227}\u{2259}\u{2118}\u{1d534}\u{1d568}\u{2118}\
     \u{2240}\u{2240}\u{1d4cc}\u{22c2}\u{25ef}\u{22c3}\u{25bd}\u{1d535}\u{27fa}\u{27f7}\
     \u{3be}\u{27f8}\u{27f5}\u{27fc}\u{22fb}\u{2a00}\u{1d569}\u{2a01}\u{2a02}\u{27f9}\u{27f6}\
     \u{1d4cd}\u{2a06}\u{2a04}\u{25b3}\u{22c1}\u{22c0}\u{fd}\u{44f}\u{177}\u{44b}\u{a5}\
     \u{1d536}\u{457}\u{1d56a}\u{1d4ce}\u{44e}\u{ff}\u{17a}\u{17e}\u{437}\u{17c}\u{2128}\
     \u{3b6}\u{1d537}\u{436}\u{21dd}\u{1d56b}\u{1d4cf}\u{200d}\u{200c}";

/// Where each name's characters end in [`VALUES`], in bytes.
#[rustfmt::skip]
pub(super) static VALUE_ENDS: [u16; COUNT] = [
    2, 3, 5, 7, 9, 11, 15, 17, 19, 21, 24, 26, 30, 33, 35, 39, 42, 44, 46, 49, 52, 55, 57, 60,
    63, 65, 69, 73, 75, 78, 81, 83, 85, 87, 90, 93, 96, 98, 100, 102, 105, 107, 109, 111, 114,
    116, 119, 122, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 168,
    171, 174, 177, 180, 182, 184, 186, 189, 192, 195, 197, 199, 202, 204, 208, 210, 212, 214,
    215, 217, 220, 223, 227, 229, 232, 235, 238, 240, 243, 246, 249, 252, 255, 258, 261, 264,
    267, 270, 273, 276, 279, 282, 285, 287, 290, 293, 296, 299, 302, 305, 308, 311, 314, 317,
    321, 323, 325, 327, 329, 331, 333, 335, 337, 341, 343, 346, 348, 351, 354, 356, 360, 362,
    365, 368, 371, 374, 377, 379, 381, 384, 387, 389, 393, 396, 399, 403, 406, 409, 412, 414,
    415, 417, 419, 421, 423, 425, 427, 429, 433, 436, 440, 443, 446, 449, 452, 455, 458, 461,
    465, 468, 470, 472, 473, 475, 478, 481, 484, 487, 490, 492, 495, 498, 500, 502, 504, 506,
    508, 510, 512, 515, 517, 520, 522, 525, 528, 531, 534, 537, 540, 543, 545, 549, 551, 554,
    556, 558, 560, 562, 564, 568, 572, 576, 578, 580, 582, 584, 586, 588, 590, 594, 598, 602,
    604, 605, 607, 609, 612, 615, 618, 620, 622, 624, 627, 630, 633, 636, 639, 642, 645, 648,
    651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681, 684, 687, 690, 693, 696, 699, 702,
    705, 708, 711, 714, 717, 720, 724, 727, 730, 732, 735, 738, 741, 744, 747, 750, 754, 757,
    760, 763, 766, 768, 771, 774, 776, 779, 782, 786, 789, 793, 796, 798, 800, 802, 804, 806,
    808, 811, 814, 817, 820, 823, 826, 827, 831, 834, 836, 839, 842, 845, 848, 851, 854, 857,
    862, 865, 868, 871, 876, 881, 884, 889, 892, 897, 902, 905, 910, 913, 916, 919, 922, 927,
    932, 935, 940, 945, 948, 953, 956, 959, 962, 967, 970, 975, 978, 983, 986, 992, 995, 998,
    1003, 1006, 1011, 1017, 1020, 1023, 1026, 1029, 1032, 1035, 1039, 1041, 1043, 1045, 1047,
    1049, 1051, 1053, 1057, 1059, 1061, 1063, 1065, 1069, 1072, 1075, 1078, 1082, 1084, 1086,
    1089, 1091, 1094, 1097, 1100, 1103, 1106, 1108, 1112, 1114, 1116, 1118, 1121, 1124, 1127,
    1130, 1133, 1136, 1139, 1142, 1145, 1148, 1151, 1155, 1157, 1158, 1162, 1165, 1169, 1172,
    1174, 1176, 1179, 1182, 1185, 1187, 1189, 1191, 1194, 1197, 1200, 1203, 1206, 1208, 1211,
    1214, 1217, 1220, 1223, 1226, 1229, 1232, 1235, 1238, 1241, 1244, 1247, 1250, 1253, 1256,
    1259, 1262, 1265, 1268, 1271, 1274, 1277, 1280, 1283, 1286, 1289, 1292, 1295, 1297, 1299,
    1301, 1303, 1306, 1308, 1310, 1312, 1314, 1318, 1321, 1324, 1327, 1330, 1332, 1335, 1339,
    1342, 1345, 1348, 1351, 1354, 1357, 1360, 1363, 1367, 1370, 1373, 1376, 1379, 1382, 1385,
    1388, 1391, 1394, 1397, 1400, 1403, 1406, 1409, 1411, 1414, 1416, 1418, 1419, 1421, 1423,
    1425, 1427, 1431, 1434, 1436, 1442, 1445, 1448, 1451, 1454, 1457, 1461, 1464, 1468, 1470,
    1472, 1475, 1478, 1480, 1482, 1484, 1486, 1488, 1492, 1494, 1496, 1497, 1500, 1503, 1506,
    1509, 1512, 1514, 1518, 1521, 1524, 1527, 1530, 1533, 1536, 1539, 1542, 1545, 1548, 1551,
    1553, 1555, 1557, 1561, 1563, 1565, 1568, 1571, 1573, 1576, 1579, 1582, 1585, 1588, 1591,
    1592, 1595, 1598, 1601, 1605, 1609, 1613, 1616, 1618, 1621, 1625, 1629, 1633, 1637, 1639,
    1643, 1647, 1649, 1651, 1653, 1655, 1657, 1659, 1663, 1667, 1671, 1673, 1675, 1677, 1679,
    1681, 1683, 1686, 1688, 1691, 1694, 1698, 1700, 1702, 1705, 1710, 1713, 1715, 1717, 1719,
    1721, 1724, 1728, 1730, 1733, 1736, 1738, 1740, 1743, 1744, 1747, 1750, 1753, 1756, 1759,
    1762, 1765, 1768, 1771, 1774, 1777, 1780, 1783, 1786, 1789, 1792, 1795, 1798, 1801, 1804,
    1807, 1809, 1812, 1814, 1818, 1821, 1824, 1827, 1830, 1833, 1834, 1837, 1840, 1842, 1846,
    1847, 1850, 1853, 1855, 1857, 1860, 1863, 1866, 1869, 1871, 1874, 1877, 1880, 1883, 1886,
    1889, 1892, 1895, 1898, 1900, 1903, 1906, 1909, 1912, 1914, 1917, 1919, 1922, 1925, 1929,
    1932, 1935, 1938, 1941, 1944, 1947, 1950, 1953, 1956, 1959, 1962, 1965, 1968, 1971, 1974,
    1977, 1980, 1983, 1986, 1989, 1992, 1995, 1998, 2001, 2004, 2008, 2014, 2017, 2021, 2024,
    2027, 2030, 2033, 2036, 2039, 2042, 2045, 2048, 2051, 2054, 2057, 2060, 2063, 2066, 2069,
    2072, 2075, 2078, 2081, 2084, 2087, 2090, 2093, 2096, 2099, 2102, 2105, 2108, 2111, 2114,
    2117, 2120, 2123, 2126, 2129, 2132, 2135, 2138, 2141, 2144, 2147, 2150, 2153, 2156, 2159,
    2162, 2165, 2167, 2169, 2173, 2176, 2179, 2182, 2183, 2186, 2189, 2192, 2195, 2198, 2201,
    2204, 2207, 2209, 2212, 2215, 2218, 2221, 2224, 2227, 2233, 2236, 2238, 2241, 2243, 2245,
    2247, 2250, 2253, 2255, 2257, 2260, 2262, 2264, 2268, 2270, 2273, 2276, 2278, 2281, 2284,
    2286, 2289, 2292, 2295, 2297, 2300, 2303, 2306, 2309, 2312, 2315, 2318, 2321, 2324, 2327,
    2328, 2331, 2334, 2335, 2336, 2339, 2342, 2345, 2348, 2351, 2354, 2357, 2361, 2364, 2366,
    2369, 2372, 2375, 2379, 2382, 2385, 2388, 2391, 2394, 2397, 2400, 2403, 2406, 2409, 2412,
    2415, 2418, 2421, 2424, 2427, 2430, 2436, 2439, 2442, 2445, 2448, 2451, 2454, 2456, 2459,
    2462, 2465, 2468, 2471, 2474, 2477, 2480, 2483, 2486, 2489, 2492, 2495, 2498, 2501, 2503,
    2505, 2507, 2510, 2513, 2516, 2519, 2521, 2523, 2526, 2529, 2533, 2536, 2539, 2542, 2545,
    2548, 2551, 2553, 2555, 2558, 2560, 2562, 2565, 2568, 2570, 2573, 2576, 2577, 2581, 2583,
    2586, 2589, 2592, 2595, 2598, 2601, 2604, 2607, 2610, 2613, 2616, 2619, 2622, 2626, 2628,
    2631, 2633, 2636, 2639, 2642, 2645, 2648, 2651, 2653, 2656, 2659, 2662, 2664, 2667, 2669,
    2672, 2674, 2677, 2679, 2681, 2684, 2687, 2691, 2694, 2696, 2699, 2702, 2705, 2708, 2711,
    2714, 2717, 2719, 2722, 2725, 2728, 2731, 2734, 2737, 2739, 2742, 2744, 2748, 2751, 2754,
    2757, 2759, 2761, 2763, 2766, 2769, 2772, 2775, 2778, 2779, 2782, 2785, 2788, 2791, 2794,
    2797, 2800, 2803, 2806, 2808, 2810, 2812, 2815, 2816, 2819, 2822, 2825, 2828, 2830, 2833,
    2836, 2839, 2842, 2846, 2849, 2851, 2854, 2857, 2860, 2862, 2866, 2869, 2872, 2875, 2878,
    2880, 2883, 2885, 2888, 2891, 2894, 2897, 2900, 2902, 2905, 2908, 2911, 2914, 2917, 2920,
    2923, 2926, 2930, 2933, 2936, 2938, 2940, 2942, 2945, 2947, 2949, 2951, 2953, 2956, 2959,
    2962, 2965, 2968, 2971, 2974, 2977, 2980, 2983, 2989, 2992, 2996, 2999, 3002, 3005, 3007,
    3010, 3013, 3016, 3019, 3022, 3025, 3028, 3031, 3034, 3037, 3040, 3044, 3045, 3048, 3051,
    3054, 3057, 3058, 3061, 3064, 3067, 3070, 3073, 3076, 3079, 3082, 3085, 3088, 3091, 3094,
    3100, 3106, 3109, 3112, 3114, 3117, 3119, 3122, 3125, 3128, 3131, 3133, 3136, 3139, 3142,
    3145, 3149, 3152, 3155, 3158, 3161, 3164, 3167, 3171, 3174, 3178, 3181, 3183, 3186, 3189,
    3191, 3194, 3196, 3198, 3200, 3202, 3205, 3209, 3211, 3214, 3217, 3220, 3223, 3226, 3228,
    3230, 3233, 3236, 3239, 3241, 3244, 3246, 3249, 3252, 3255, 3258, 3260, 3263, 3266, 3269,
    3272, 3275, 3278, 3280, 3282, 3286, 3288, 3291, 3293, 3297, 3300, 3303, 3306, 3309, 3312,
    3315, 3318, 3320, 3322, 3324, 3326, 3328, 3332, 3334, 3338, 3342, 3344, 3346, 3348, 3350,
    3352, 3354, 3358, 3360, 3362, 3364, 3368, 3372, 3375, 3378, 3381, 3384, 3387, 3390, 3393,
    3395, 3398, 3401, 3403, 3406, 3409, 3412, 3415, 3417, 3420, 3423, 3426, 3429, 3432, 3435,
    3438, 3441, 3444, 3447, 3450, 3453, 3459, 3462, 3465, 3466, 3467, 3470, 3473, 3476, 3478,
    3480, 3483, 3484, 3486, 3489, 3492, 3495, 3498, 3501, 3504, 3507, 3510, 3513, 3516, 3519,
    3522, 3525, 3528, 3531, 3534, 3537, 3540, 3543, 3546, 3549, 3552, 3555, 3558, 3561, 3564,
    3570, 3573, 3576, 3579, 3582, 3585, 3588, 3591, 3594, 3597, 3601, 3604, 3607, 3610, 3613,
    3616, 3619, 3621, 3624, 3627, 3630, 3633, 3636, 3638, 3641, 3644, 3647, 3650, 3653, 3656,
    3659, 3662, 3665, 3668, 3671, 3674, 3677, 3680, 3683, 3686, 3689, 3692, 3695, 3699, 3702,
    3705, 3708, 3709, 3712, 3715, 3718, 3719, 3722, 3725, 3728, 3731, 3734, 3737, 3740, 3743,
    3747, 3750, 3753, 3756, 3759, 3760, 3763, 3766, 3768, 3769, 3772, 3775, 3778, 3781, 3784,
    3787, 3790, 3793, 3796, 3799, 3802, 3805, 3808, 3814, 3820, 3823, 3825, 3828, 3831, 3834,
    3837, 3840, 3843, 3846, 3849, 3852, 3855, 3857, 3860, 3863, 3867, 3870, 3872, 3875, 3876,
    3879, 3881, 3884, 3887, 3890, 3893, 3896, 3899, 3902, 3905, 3909, 3912, 3916, 3919, 3921,
    3924, 3927, 3932, 3938, 3943, 3946, 3949, 3954, 3960, 3965, 3968, 3971, 3974, 3977, 3979,
    3985, 3988, 3993, 3998, 4000, 4003, 4006, 4009, 4012, 4014, 4019, 4024, 4027, 4029, 4031,
    4034, 4039, 4042, 4044, 4047, 4050, 4053, 4056, 4059, 4062, 4067, 4070, 4073, 4078, 4081,
    4084, 4088, 4093, 4096, 4099, 4104, 4109, 4114, 4117, 4120, 4123, 4126, 4129, 4132, 4135,
    4138, 4141, 4144, 4146, 4149, 4154, 4157, 4160, 4163, 4166, 4169, 4172, 4177, 4182, 4187,
    4190, 4193, 4196, 4199, 4202, 4205, 4209, 4211, 4214, 4219, 4224, 4227, 4230, 4233, 4236,
    4239, 4242, 4245, 4248, 4251, 4257, 4262, 4265, 4268, 4271, 4276, 4279, 4284, 4287, 4290,
    4295, 4300, 4303, 4306, 4309, 4312, 4315, 4320, 4324, 4327, 4330, 4333, 4336, 4339, 4342,
    4345, 4348, 4351, 4354, 4359, 4362, 4368, 4371, 4376, 4379, 4384, 4387, 4392, 4395, 4401,
    4404, 4409, 4412, 4414, 4417, 4420, 4423, 4426, 4429, 4431, 4432, 4435, 4438, 4441, 4444,
    4450, 4453, 4459, 4463, 4466, 4469, 4475, 4479, 4485, 4488, 4494, 4500, 4503, 4506, 4509,
    4512, 4515, 4518, 4520, 4523, 4526, 4528, 4530, 4533, 4535, 4538, 4541, 4544, 4546, 4549,
    4553, 4555, 4557, 4560, 4563, 4565, 4568, 4571, 4574, 4577, 4580, 4583, 4585, 4587, 4589,
    4592, 4595, 4599, 4602, 4605, 4608, 4611, 4614, 4617, 4620, 4623, 4625, 4627, 4630, 4633,
    4636, 4639, 4642, 4644, 4647, 4649, 4652, 4655, 4657, 4660, 4663, 4665, 4668, 4671, 4674,
    4677, 4679, 4680, 4681, 4684, 4687, 4690, 4694, 4696, 4698, 4701, 4704, 4706, 4709, 4711,
    4714, 4717, 4720, 4721, 4724, 4727, 4730, 4733, 4736, 4739, 4741, 4744, 4747, 4749, 4752,
    4756, 4758, 4761, 4764, 4767, 4770, 4773, 4776, 4779, 4782, 4785, 4788, 4791, 4794, 4797,
    4800, 4803, 4806, 4809, 4812, 4815, 4818, 4821, 4824, 4827, 4830, 4833, 4836, 4840, 4842,
    4845, 4849, 4852, 4856, 4859, 4863, 4866, 4869, 4870, 4873, 4874, 4877, 4880, 4883, 4886,
    4889, 4894, 4896, 4899, 4902, 4905, 4908, 4911, 4914, 4916, 4919, 4922, 4925, 4928, 4931,
    4934, 4937, 4940, 4943, 4946, 4949, 4952, 4955, 4958, 4961, 4964, 4967, 4968, 4969, 4972,
    4975, 4978, 4980, 4982, 4985, 4986, 4988, 4991, 4994, 4997, 5000, 5003, 5006, 5009, 5012,
    5015, 5018, 5020, 5023, 5026, 5030, 5033, 5036, 5039, 5041, 5043, 5046, 5049, 5052, 5055,
    5058, 5061, 5064, 5067, 5070, 5072, 5075, 5078, 5081, 5084, 5087, 5090, 5093, 5096, 5099,
    5102, 5105, 5109, 5112, 5115, 5116, 5119, 5122, 5125, 5128, 5132, 5135, 5136, 5139, 5142,
    5145, 5148, 5151, 5154, 5157, 5160, 5163, 5166, 5168, 5171, 5174, 5177, 5180, 5182, 5185,
    5188, 5190, 5192, 5195, 5198, 5201, 5204, 5207, 5209, 5212, 5215, 5218, 5221, 5224, 5227,
    5230, 5232, 5233, 5236, 5239, 5242, 5245, 5249, 5252, 5255, 5257, 5259, 5262, 5265, 5267,
    5269, 5271, 5273, 5276, 5279, 5282, 5285, 5288, 5291, 5294, 5297, 5300, 5303, 5306, 5309,
    5312, 5315, 5318, 5321, 5324, 5327, 5330, 5336, 5338, 5339, 5342, 5345, 5349, 5352, 5355,
    5358, 5361, 5367, 5370, 5376, 5379, 5382, 5385, 5388, 5391, 5394, 5397, 5400, 5403, 5406,
    5409, 5412, 5415, 5419, 5422, 5425, 5428, 5431, 5434, 5436, 5438, 5440, 5443, 5446, 5449,
    5452, 5455, 5458, 5461, 5464, 5467, 5470, 5473, 5476, 5479, 5482, 5485, 5488, 5491, 5494,
    5497, 5500, 5503, 5506, 5509, 5512, 5515, 5518, 5521, 5524, 5527, 5529, 5531, 5533, 5536,
    5539, 5542, 5545, 5548, 5551, 5554, 5557, 5560, 5563, 5566, 5569, 5572, 5575, 5578, 5581,
    5584, 5587, 5590, 5593, 5596, 5599, 5602, 5605, 5608, 5610, 5613, 5615, 5618, 5620, 5622,
    5624, 5627, 5630, 5634, 5637, 5640, 5642, 5644, 5646, 5649, 5652, 5655, 5658, 5661, 5663,
    5665, 5667, 5670, 5673, 5676, 5679, 5682, 5685, 5688, 5691, 5695, 5698, 5701, 5704, 5707,
    5710, 5713, 5716, 5719, 5722, 5725, 5728, 5731, 5734, 5737, 5740, 5743, 5746, 5749, 5753,
    5755, 5757, 5759, 5762, 5765, 5768, 5771, 5774, 5776, 5779, 5781, 5783, 5785, 5787, 5790,
    5792, 5795, 5798, 5802, 5804, 5807, 5810, 5813, 5816, 5819, 5822, 5825, 5827, 5829, 5831,
    5835, 5838, 5841, 5844, 5847, 5850, 5852, 5854, 5856, 5859, 5862, 5865, 5868, 5870, 5873,
    5877, 5880, 5882, 5885, 5888, 5891, 5893, 5896, 5899, 5902, 5905, 5908, 5911, 5913, 5915,
    5918, 5920, 5922, 5925, 5928, 5930, 5932, 5938, 5944, 5950, 5956, 5958, 5961, 5964, 5966,
    5969, 5972, 5975, 5978, 5981, 5982, 5983, 5987, 5990, 5996, 6002, 6006, 6009, 6012, 6016,
    6022, 6028, 6034, 6040, 6043, 6045, 6048, 6051, 6054, 6057, 6061, 6065, 6068, 6071, 6074,
    6078, 6081, 6084, 6087, 6090, 6094, 6097, 6100, 6102, 6105, 6108, 6111, 6114, 6117, 6121,
    6124, 6127, 6130, 6133, 6137, 6140, 6143, 6146, 6149, 6152, 6154, 6156, 6158, 6160, 6162,
    6166, 6168, 6172, 6176, 6178, 6180, 6182, 6184, 6186, 6188, 6191, 6193, 6197, 6199, 6202,
    6206, 6210, 6213, 6216,
];
